### ISSUE TITLE
How to retrieve app set languages?

### ISSUE THREAD

**Issue by dkeulen** [Squidex/squidex#101]
Hi,

I used Squidex for a while, but i started to wonder about something.

How do you retrieve the set languages of your app? Like what url/api end point should it try to contact for that info?
So far I can’t find this in the (swagger) api docs or anywhere else (except how to get Squidex supported languages/iso codes etc).

I was able to figure out some url to talk to for my own app by checking the xhr requests of Squidex in console, that contains what i want to retrieve. But the request is done with its own token, and my client (token) does not have acces to that url/endpoint.

Any info would be appreciated.

**Comment by SebastianStehle** [comment]
Have you checked this docs: https://cloud.squidex.io/api/docs#operation/AppLanguages_GetLanguages ?

It depends on the permissions, there is: Owner, Developer, Editor, Reader ... the client is either Editor or Reader (depends what you have set), so this endpoint can be used by your client. (I have to change it to Reader I think).

**Comment by dkeulen** [comment]
@SebastianStehle Thanks,

As you mention, it does require the scope Editor, for the client to be able to get the languages.
However, i did have it set to read only there for it did not work for my client. So thanks for pointing that out.

The thing is i would have rather have my client set to ready only, given the way my app is set up.
And it sounds kinda weird that my read-only client can't get the language (i mean plain simply thinking about getting my app data, read-only should be able to in my opinion).
So yes i would absolutely LOVE if you would make it able for the read-only clients to get the language please!

**Comment by SebastianStehle** [comment]
I am on vacation and cannot do it before friday. But here is the code: https://github.com/Squidex/squidex/blob/master/src/Squidex/Controllers/Api/Apps/AppLanguagesController.cs

You just have to replace AppMustBeEditor with AppMustBeOwner in Line 47

**Comment by dkeulen** [comment]
@SebastianStehle 

Thanks for the awesome level of assistance/support.
But i am making use of the cloud hosted solution now. Guess i can't edit that environment so far i know (or are you talking about making a pr?).

Anyways don't worry about it for now, first enjoy your vacation!

**Comment by SebastianStehle** [comment]
Don't need a PR for this. Will fix it on Friday.
