### ISSUE TITLE
Cannot update display name or other claims

### ISSUE THREAD

**Issue by Avd6977** [Squidex/squidex#105]
With the change from WrappedIdentityUser to MongoUser, the function to remove claims before setting the new one changed and is no longer working.

**Comment by SebastianStehle** [comment]
Which function do you mean?

**Comment by Avd6977** [comment]
Squidex.Domain.Users.MongoDb.RemoveClaim (or SetClaim)

The claim checks both type and value are still the same.

**Comment by Avd6977** [comment]
Before it used
Claims.RemoveAll(x => string.Equals(x.Type, claim.Type, StringComparison.OrdinalIgnoreCase));

**Comment by SebastianStehle** [comment]
I see.

**Comment by SebastianStehle** [comment]
Will fix in half an hour.
