### ISSUE TITLE
Permissions based on language

### ISSUE THREAD

**Issue by BoasE** [Squidex/squidex#106]
When having more then one language it would be very interessting to limit user to only change values of a given languages.

The reason is that when you someone who is responsible for the russian language isn't  the same who makes spanish translations. Therefore it would be very good to have a optional permission based on the language of the contents

**Comment by SebastianStehle** [comment]
You could do it with scripts.

**Comment by SebastianStehle** [comment]
https://trello.com/c/2NuCWGB2/65-permission-based-on-language
