### ISSUE TITLE
[Idea] Automatic updates

### ISSUE THREAD

**Issue by pushrbx** [Squidex/squidex#108]
It would be nice to have a system in place to offer updates on the admin panel, and squidex would update itself.
I can imagine a way to do this:
- Create a lock file and a middleware which would check if the lock file exists. If the lock file exists the middleware would prevent the request to proceed, and it would return a predefined response to the browser.
- Create a logic which would use a lib from nuget for fetching the latest version from git.
- Also something is needed to put the files in place, and restart the kestrel process.

I'm not sure if the above is possible to do within a single request context.
I haven't done too much research in this topic, but I'm sure that there has to be a nuget package or something else out there to accomplish this.

**Comment by SebastianStehle** [comment]
Yes, would be great and a challenge :)

It depends a lot on the Hosting context I think, e.g. IIS has the app_offline file. Or you need another service on your machine to make the update. Will think about it.

**Comment by pushrbx** [comment]
The project can take a route like the discourse project did: they encourage everyone to use their docker image. This way the problem of variable hosting environments could be solved.

**Comment by SebastianStehle** [comment]
Partially, but Docker has different deployment options too: Compose, Swarm, Kubernetes, Single Instance ...

**Comment by pushrbx** [comment]
They are using pup scripts, and that one allows many configurations.

**Comment by SebastianStehle** [comment]
Do you have a link?

**Comment by pushrbx** [comment]
https://github.com/discourse/discourse_docker
https://github.com/samsaffron/pups
and interesting read, which might give you an idea: https://samsaffron.com/archive/2013/11/07/discourse-in-a-docker-container
