### ISSUE TITLE
Default values with valid validation pattern are not displaying when saving content

### ISSUE THREAD

**Issue by Avd6977** [Squidex/squidex#109]
Createa a schema with a string input field
Set a validation pattern (one below is a zip code)
\\d{5}([\\-]\\d{4})?$
Set a valid default value (12345)
Create a content element of that schema and leave the zip code input blank (should take default value)
Notice it saves but the default value does not appear.

**Comment by SebastianStehle** [comment]
I guess it is because on an empty string. Does it also happen without the Regex?

**Comment by SebastianStehle** [comment]
Btw: Are you sure that your regex is valid? Should it not start with ^ ?

**Comment by Avd6977** [comment]
It did not happen with no regex. I should start with ^, I just missed it on the copy paste :)

**Comment by SebastianStehle** [comment]
I changed it to apply the default value for empty string too. I have forgotten that I add ^ and $ automatically :D

**Comment by SebastianStehle** [comment]
https://github.com/Squidex/squidex/blob/9753cfbeacecff9d08ebcb6b551831dd7362b050/src/Squidex.Domain.Apps.Core/Schemas/Validators/PatternValidator.cs
