### ISSUE TITLE
can't create schema content via api client (err: forbidden)

### ISSUE THREAD

**Issue by neeasade** [Squidex/squidex#110]
Hi, I'm trying to create a schema via the api on cloud.squidex.io -- 

I created a client in app (nathantestapp), and got a token with:
``` json
            {
                "grant_type": "client_credentials",
                "client_id": "<client_id>",
                "client_secret": "<client_secret>",
                "scope": "squidex-api"
            }
```

I tested the validity of token by requesting a list of schemas in my app(returned the list as expected), and then tried to create a schema with a field by posting to https://cloud.squidex.io/api/apps/nathantestapp/schemas with the following:

``` json
{
  "Name": "apicreate",
  "Properties": {
    "Label": null,
    "Hints": null
  },
  "Fields": [
    {
      "Name": "testAddField",
      "IsHidden": false,
      "IsLocked": false,
      "IsDisabled": false,
      "Partitioning": null,
      "Properties": {
        "fieldType": "Boolean",
        "DefaultValue": null,
        "Editor": "Checkbox",
        "Label": null,
        "Hints": null,
        "Placeholder": null,
        "IsRequired": false,
        "IsListField": false,
        "Partitioning": null
      }
    }
  ]
}
```

and the response is forbidden/empty string -- am I requesting the wrong scope initially?

edit: this is what I'm referencing: https://cloud.squidex.io/api/content/nathantestapp/docs#section/Authentication

Thanks,
Nathan

**Comment by SebastianStehle** [comment]
I justed tested it, everything works fine for me. Can you create a token via the Administration UI?

**Comment by neeasade** [comment]
Do you mean in the UI under app settings? I do not see a place for token in Admin UI -- only users and consumers.

**Comment by SebastianStehle** [comment]
There is a button for each client "Create Token": https://docs.squidex.io/04-guides/04-postman.html

**Comment by neeasade** [comment]
ah! ok -- using that I still get the same issue (placed result verbatim in my 'Authorization' header) -- I can still read contents fine (get listings of schemas or contents) I just can't post for some reason.

**Comment by SebastianStehle** [comment]
Is your Client readonly?

**Comment by neeasade** [comment]
negative -- 

![image](https://user-images.githubusercontent.com/3747396/30447487-ebed5f0c-9951-11e7-93f0-b8ee047326cb.png)

**Comment by SebastianStehle** [comment]
Mhm, no :D

**Comment by SebastianStehle** [comment]
I am confused now. My internet connection in the train is not stable enough to open a connection to my kubernetes cluster. 

Can you invite me to your App?

**Comment by SebastianStehle** [comment]
Now it worked. I checked the DB and everything looks good...

**Comment by neeasade** [comment]
added -- FWIW I'm doing this from c# with an HttpClient() -- I'm making my payload like:

``` c#
        private StringContent Encode(object toEncode)
        {
            return new StringContent(JsonConvert.SerializeObject(toEncode));
        }
```

and 


```
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

client.PostAsync(<url>, Encode(payload))
```

**Comment by SebastianStehle** [comment]
I mean I was able to connect to the DB ;)

**Comment by SebastianStehle** [comment]
And how do you add the token?

**Comment by neeasade** [comment]
oh :)

``` c#
            var testtoken = "<value from get token UI>";
            client.DefaultRequestHeaders.Add("Authorization", testtoken);
```

**Comment by SebastianStehle** [comment]
Looks good. Can you send me the token to sebastian@squidex.io or add me to the app as Owner?

**Comment by neeasade** [comment]
Made you an Owner

**Comment by SebastianStehle** [comment]
Which user have you added?

**Comment by SebastianStehle** [comment]
The wrong one ... does not matter. I was shocked, becuase I thought there is a bug :D

**Comment by neeasade** [comment]
just switched them

**Comment by SebastianStehle** [comment]
So much stress after 8 hours of travelling around :D

**Comment by SebastianStehle** [comment]
I tested it with Postman and it works:

	REQUEST:
	
	POST https://cloud.squidex.io/api/content/nathantestapp/content-type-recipe HTTP/1.1
	cache-control: no-cache
	Postman-Token: bc94dc05-d953-41dc-a83d-d53c3e1403e4
	Authorization: Bearer *************************
	Content-Type: application/json
	User-Agent: PostmanRuntime/6.3.2
	Accept: */*
	Host: cloud.squidex.io
	cookie: __cfduid=d3aa465fdaf4e1a19863c675faac353681505412498
	accept-encoding: gzip, deflate
	content-length: 3
	Connection: close

	{
	}

	RESPONSE:
	
	HTTP/1.1 201 Created
	Date: Thu, 14 Sep 2017 19:11:06 GMT
	Content-Type: application/json; charset=utf-8
	Transfer-Encoding: chunked
	Connection: close
	ETag: 0
	Location: https://cloud.squidex.io/api/content/nathantestapp/content-type-recipe/7b2911cd-67ec-44f9-a2fe-dedb481d3b29
	Server: cloudflare-nginx
	CF-RAY: 39e5a671fb016343-FRA

	10d
	{"id":"7b2911cd-67ec-44f9-a2fe-dedb481d3b29","createdBy":"client:nathantestapp:testcreate","lastModifiedBy":"client:nathantestapp:testcreate","data":{"image":{"iv":[]}},"created":"2017-09-14T19:11:06Z","lastModified":"2017-09-14T19:11:06Z","status":"Draft","version":0}
	0

**Comment by neeasade** [comment]
I'm not trying to create content though -- I'm trying to create a new schema

**Comment by SebastianStehle** [comment]
Lol, okay. It is not possible as Client at the moment

**Comment by neeasade** [comment]
Oh, alrighty then

**Comment by neeasade** [comment]
Can clients add assets?

**Comment by SebastianStehle** [comment]
Yes.

There are four roles per App:

* **Owner**: Can do everything
* **Developer**: Can manage schemas, contents, webhooks and assets
* **Editor**: Can manage contents and assets
* **Reader**: Can read contents and assets.

Users are either, Owners: Developers or Editors.
Clients are either Editors or Readers

But I could change it to allow making clients developers as well. I would prefer not to make them Owners
