### ISSUE TITLE
Migration of database from old version of squidex to the new version

### ISSUE THREAD

**Issue by pushrbx** [Squidex/squidex#112]
Today I tried to migrate to the new version of squidex but it seems that some fields have changed since 4th of August. So far I had to add the `ContributorIds` field to the `Projection_Apps` document in mongodb. On the admin panel I can't see my content, but they are in the db. When I try to add a new content I get an exception saying "type ContentCreatedEvent doesn't exist". My content is in MongoDB.
Squidex can connect to GetEventStore, the position gets updated in there, but I guess that squidex can't read back the projections for some reason.
I tried to reset the consumers, but they just get stuck in "resetting" state. I tried to reset the content projection on the admin panel of ES, but no luck. Now I got that far that under the Consumers panel I don't see any exceptions popping up.

With this issue I don't intend to suggest a possible bug, obviously the upgrade from older version is the culprit, rather I'm looking for an answer for the following questions:
1. What has changed for ES and MongoDB recently? Is there some field that I should add or modify?
2. If nothing has changed, how can I reset my setup without loosing data?

![scr1](https://archiverbx.blob.core.windows.net/public/Screenshot_2017-09-17_20-39-40.png)

My setup:
Docker: no
Azure App Service
MongoDB and ES runs on a VM on azure.

**Comment by SebastianStehle** [comment]
1. Nothing ;)
2. You could delete the EventPosition collection and all Projection_ Collections

**Comment by pushrbx** [comment]
I've deleted them. Now it shows nothing. When I reset the projections in ES squidex doesn't recreate the collections in mongodb. So now what? 😄

**Comment by SebastianStehle** [comment]
There should be no need to Change something in ES. I will have a look when I am Home. Waiting at the Airport at the moment.

Sorry

**Comment by pushrbx** [comment]
No worries, have a nice trip. I should be apologizing. 😄

**Comment by SebastianStehle** [comment]
Great
