### ISSUE TITLE
Error when saving content with Edit Content screen open

### ISSUE THREAD

**Issue by kwyss88** [Squidex/squidex#116]
**How to reproduce:**

1. Go to the content listing page of any schema.
2. Click on an existing content item to open the Edit Content form.
3. _While the Edit Content form is open,_ Publish/Unpublish the item from the action menu in the listing.
4. Change a field value on the Edit Content form for the same item and try to Save.
5. Error gets thrown.

**Alternative way to reproduce:**

1. Go to the content listing page of any schema.
2. Click on an existing content item to open the Edit Content form.
3. Change a field value and Save, _but leave the Edit Content form open._
4. Try Publishing/Unpublishing the same content item from the action menu in the listing.
5. Error gets thrown.

**Comment by SebastianStehle** [comment]
Thank you very much. The editor on the right side does not get the updated version after a publish and therefore fails to make the update.

**Comment by kwyss88** [comment]
It appears you may have only fixed the first way to re-create the error. If you follow these steps, it still happens:

**Alternative way to reproduce:**

1. Go to the content listing page of any schema.
2. Click on an existing content item to open the Edit Content form.
3. Change a field value and Save, but leave the Edit Content form open.
4. Try Publishing/Unpublishing the same content item from the action menu in the listing.
5. Error gets thrown.

**Comment by SebastianStehle** [comment]
Yes
