### ISSUE TITLE
Items for reference field don't show in admin panel

### ISSUE THREAD

**Issue by pushrbx** [Squidex/squidex#119]
I have a schema in the database which has a reference field. If that field has more than around 10 item (not sure), then they don't display on the admin panel.

In my case it has 61 items, and they don't show :
![image](https://user-images.githubusercontent.com/6832715/30787921-3f269166-a18b-11e7-83ba-f7aaa7ad3257.png)
But I can see them in the db:
![image](https://user-images.githubusercontent.com/6832715/30787923-52ea1844-a18b-11e7-9f70-3edaf449ee6a.png)

I'm using the latest version of squidex.  

Repro steps:
1. Create a schema with a reference field. (`Schema_A`)
2. Create another schema which will be the referenced in the previously created schema. (`Schema_B`)
3. add around 30 items to `Schema_B`
4. add an item to `Schema_A`   (`item_d`)
5. add the items from `Schema_B` to `item_d`
5. check `item_d` in the Contents menu, to see if the references display.

**Comment by SebastianStehle** [comment]
Everything published?

**Comment by pushrbx** [comment]
yes, everything is published.

**Comment by SebastianStehle** [comment]
Should be easy to fix, will do it this afternoon (after StarTrek :D)
