### ISSUE TITLE
What's the default behavior for GraphQL to return references?

### ISSUE THREAD

**Issue by pushrbx** [Squidex/squidex#120]
Same situation/setup as in issue #119 , I have a reference field with lot's of items, and in GraphQL I can only get the first 20 reference instead of all the 61. Is this the expected behavior? Or is it because they have been cached? Or do I have to provide something extra in my query?

**Comment by SebastianStehle** [comment]
It is a bug, 20 is the default: https://github.com/Squidex/squidex/blob/master/src/Squidex.Domain.Apps.Read.MongoDb/Contents/Visitors/FindExtensions.cs

**Comment by SebastianStehle** [comment]
Stupid idea to merge both queries into one method.
