### ISSUE TITLE
webhooks disappear on the cloud platform

### ISSUE THREAD

**Issue by thewebchameleon** [Squidex/squidex#121]
I created a webhook on the cloud platform and when I left the page and came back, it has vanished.

Is this suppose to happen?

**Comment by SebastianStehle** [comment]
Of course not ;) ... Just right now?

**Comment by SebastianStehle** [comment]
I can reproduce it and it will be fixed within a day. Sorry

**Comment by SebastianStehle** [comment]
Will be deployed today.

**Comment by thewebchameleon** [comment]
amazing, thank you sir!

**Comment by SebastianStehle** [comment]
You are welcome :)
