### ISSUE TITLE
Querying: How can I filter by a value of a referenced schema item?

### ISSUE THREAD

**Issue by pushrbx** [Squidex/squidex#122]
I have a schema where a `node` has `terms`. I want to query all those `nodes` which have a `term` with title `science`. How can I query this through either odata or graphql?

```json
{
    "node": {
      "title": "string",
      "description": "string",
      "terms": "term[]"
    },
    "term": {
        "title": "string"
    }
}
```

**Comment by SebastianStehle** [comment]
You cannot do it with one query. You need the id of the term, then you query the nodes :(

**Comment by pushrbx** [comment]
This makes me want to add my own controller to simplify these queries. Like a plugin or something. 😄
Something would be nice which would allow me to add extra functions for graphql. E.g. for each schema I could define custom "procedures" for querying, and I could invoke those from a graphql query.
(inspired by: https://www.howtographql.com/graphql-js/10-filtering/)

**Comment by SebastianStehle** [comment]
What kind of stored procedures?

**Comment by pushrbx** [comment]
Like the ones available right now: `query<schema_name>()`, which are generated based on the odata interface I guess. What if I could add my own function? E.g. `getAll<schema_name>WithTheseTerms(term_name: 'asd')`, so I could use it in my graphql query.

**Comment by SebastianStehle** [comment]
Pull Request Welcome ;)

**Comment by pushrbx** [comment]
I'll try to propose something in a form of pull request then.
