### ISSUE TITLE
difficulty calculating X-Signature to authenticate webhook in C#

### ISSUE THREAD

**Issue by thewebchameleon** [Squidex/squidex#124]
This may come off as a dumb question but...
How do you calculate the X-Signature when receiving webhook events?

The documentation states:
Sha256(Payload + Secret)

My concern is ONLY around the Payload value, should this be the whole JSON string? 

Here is some sample code I've written: (note: the Sha256Base64 extension comes straight from squidex)

```
[HttpPost]
public async Task<IActionResult> Receive()
{
    var secret = "some-value";
    Request.Headers.TryGetValue("X-Signature", out StringValues signature);

    using (var reader = new StreamReader(Request.Body))
    {
        var txt = await reader.ReadToEndAsync();

        dynamic jObject = JObject.Parse(txt);
        var validatedOut = $"{jObject.payload}{secret}".Sha256Base64();
        if (validatedOut == signature)
        {
            //TODO: refresh data

            return Ok();
        }
    }
    return Unauthorized();
}
```

but the values do not match

**Comment by SebastianStehle** [comment]
Have you tried $"{txt}{secret}".Sha256Base64();` ?

**Comment by thewebchameleon** [comment]
I have tried the following and still no luck :(

```
[HttpPost]
public async Task<IActionResult> Receive()
{
    var secret = "webhook-secret";
    Request.Headers.TryGetValue("X-Signature", out StringValues signature);

    using (var reader = new StreamReader(Request.Body))
    {
        var txt = await reader.ReadToEndAsync();

        dynamic jObject = JObject.Parse(txt);
        var validatedOut = $"{jObject.payload}{secret}".Sha256Base64();

        var one = $"{jObject}{secret}".Sha256Base64();
        var two = $"{jObject.payload}{secret}".Sha256Base64();
        var three = $"{txt}{secret}".Sha256Base64();

        ....
```

**Comment by SebastianStehle** [comment]
I tested your code and it works :)

See screenshot
![untitled](https://user-images.githubusercontent.com/1236435/31057991-5da13446-a6ec-11e7-8dbb-27158ef275c4.png)

**Comment by thewebchameleon** [comment]
So the problem was me copying the request straight from the UI and pasting it into Postman, i tried removing carraige returns and spaces but still no avail.

It was solved by using ngrok and sending the event directly to my localhost. Worked instantly.

Thank you Sebastian for the support!

**Comment by thewebchameleon** [comment]
As feedback, i think the documentation is ambiguous when it states to use the Payload as there is actually a property called payload in the request.

**Comment by SebastianStehle** [comment]
You are right, changed the docs :)
