### ISSUE TITLE
Cloud content is not updating

### ISSUE THREAD

**Issue by thewebchameleon** [Squidex/squidex#125]
I can't update content on the cloud platform at the moment.

I can add content but once i publish and try to refresh the page, it disappears having not persisted to data storage

**Comment by thewebchameleon** [comment]
content is updating

**Comment by thewebchameleon** [comment]
getting the same issue, this time with uploading a new asset when updating a content item within a schema

**Comment by thewebchameleon** [comment]
so the content eventually updated after checking several hours later. Is latency perhaps the issue?

**Comment by SebastianStehle** [comment]
No the issue was that an udate in GKE broke one server

**Comment by thewebchameleon** [comment]
content is updating again
