### ISSUE TITLE
Webhook events are not reflecting on the Squidex UI

### ISSUE THREAD

**Issue by thewebchameleon** [Squidex/squidex#126]
On the Cloud platform, I have updated some content and the webhook event is not reflecting.
I have tried to delete the webhook and create a new one but events still do not reflect on the UI

**Comment by SebastianStehle** [comment]
Thank you. It is actually the same problem like this: https://github.com/Squidex/squidex/issues/125

There are some background processes that populate the read models. You can read more about this process: https://docs.squidex.io/02-architecture/01-overview.html

I will fix them today.

**Comment by thewebchameleon** [comment]
webhook events are showing again
