### ISSUE TITLE
can't update or post new content via api

### ISSUE THREAD

**Issue by marwa1994** [Squidex/squidex#127]
hello i create a new schema with name  product 
i tried to post new content or update it via api but alway i have bad model 
can you tell me what's the good model to use and can you give me an example i will be very grateful
 
Post https://cloud.squidex.io/api/content/appmarwa/product
i passed the authrization key in the header
and the object {"name":"dd","price":"44","description":"ccc"}

**Comment by SebastianStehle** [comment]
Hi,

have you had a look to the API docs of your app:

https://cloud.squidex.io/api/content/appmarwa/docs

**Comment by marwa1994** [comment]
thnx :)

**Comment by SebastianStehle** [comment]
Can I close this issue?

**Comment by marwa1994** [comment]
YES
