### ISSUE TITLE
update field of schema via api

### ISSUE THREAD

**Issue by paul19942** [Squidex/squidex#129]
i try to update a field of schema using api but i always get 403
put https://cloud.squidex.io/api/apps/appmarwa/schemas/product/fields/1
i added the key
and the json is:
{
"properties": {
"label": "string",
"hints": "string",
"placeholder": "string",
"isRequired": true,
"isListField": false,
"fieldType": "string"
}
}
can u help me please

**Comment by SebastianStehle** [comment]
Hi, you are the second user asking for it.

There are four roles:

Reader: Can query content.
Editor: Can view, update and delete content items.
Developer: Can also create, modify and delete schemas.
Owner: Can also manage settings, including adding other users.

A client can be either Reader or Editor, a user can be Editor, Developer or Owner. But I will change it this week to also allow clients to become Owners.

**Comment by paul19942** [comment]
have you change it or not yet ?

**Comment by SebastianStehle** [comment]
There is a pull request, but I have to finalize it tomorrow. I am on a trip and spend every free minute for it.

**Comment by SebastianStehle** [comment]
It has been deployed
