### ISSUE TITLE
cannot load webhooks

### ISSUE THREAD

**Issue by thewebchameleon** [Squidex/squidex#132]
getting a "Failed to load events. Please reload." error every time i browse to my webhooks.

**Comment by SebastianStehle** [comment]
Something is going really strange. I am working on it.

**Comment by SebastianStehle** [comment]
Can you check your hooks?

**Comment by thewebchameleon** [comment]
webhook events are still not reflecting on the Cloud UI

**Comment by SebastianStehle** [comment]
Fixed

**Comment by thewebchameleon** [comment]
web hooks are reflecting again. Thanks! :)
