### ISSUE TITLE
[Idea] Image resizing for assets

### ISSUE THREAD

**Issue by thewebchameleon** [Squidex/squidex#133]
Would be awesome to be able to create a resized version of an existing asset in a specified size (the aspect ratio would not change of course)

**Comment by SebastianStehle** [comment]
Hi, you can have a look how the previews are loaded and play around with it. It is already possible :)

**Comment by SebastianStehle** [comment]
Have you found it?

**Comment by thewebchameleon** [comment]
i could not but i decided to drop the feature
