### ISSUE TITLE
[Idea] Input parameter for a schema field

### ISSUE THREAD

**Issue by thewebchameleon** [Squidex/squidex#134]
**Example:**
There are multiple profiles in a schema for each user. Each user also has profiles on external sites like Github, Twitter etc. It would be redundant to keep creating `External Link` content items when only the `URL` of their `External Link` changes.

```
Profile [schema]
- Portrait [asset]
- Name [string]
- Body [rich text]
- External Links [reference field]
```

```
External Link [schema]
- Name [string]
- Icon [asset]
- URL [string] INPUT
```

So when adding an `External Links` content item to `Profile`, it would be cool to be prompted for the value of the field `URL`.

**Comment by SebastianStehle** [comment]
Don't get it

**Comment by thewebchameleon** [comment]
I've elaborated further, just spit balling here... :P

**Comment by SebastianStehle** [comment]
You want something like a join table in SQL?

**Comment by thewebchameleon** [comment]
no, something like a prompt on the Squidex UI but I've realised this doesn't actually make sense.

**Comment by SebastianStehle** [comment]
I think it makes sense. Our idea was to have nested documents for that. So you would have an array of subdocuments, each with a id to a link and the url.
