### ISSUE TITLE
my account has disappeared on the cloud platform..

### ISSUE THREAD

**Issue by thewebchameleon** [Squidex/squidex#137]
Logging in with my Microsoft account takes me to an empty workspace, my projects have disapeared

I also cannot log in via Github, i get the following error

```
Operation failed
We are really sorry that something went wrong
```

**Comment by SebastianStehle** [comment]
I tested all three account types and I cannot reproduce it :(

**Comment by SebastianStehle** [comment]
What is your email address in Squidex?

**Comment by SebastianStehle** [comment]
Fixed

**Comment by thewebchameleon** [comment]
my account has disappeared again, not sure if you're doing maintenance at this time?

**Comment by SebastianStehle** [comment]
Yes, it is just in progress, I need a UI to indicate it

**Comment by SebastianStehle** [comment]
Done. Don't worry, from the technical side it is almost impossible to loose data.
