### ISSUE TITLE
Can no longer change contributors from Owner

### ISSUE THREAD

**Issue by Avd6977** [Squidex/squidex#140]
Add a contributor to your app
See their permissions are "Editor" by default
Refresh the page and see it's now owner
Change the dropdown to Editor or Developer
It appears to change
Refresh and it's owner again.

**Comment by Avd6977** [comment]
It looks as though users aren't getting claims anymore associated with roles and it's defaulting to Owner

**Comment by SebastianStehle** [comment]
Thank you very much for your bug report.
