### ISSUE TITLE
Modifying schema after creation errors

### ISSUE THREAD

**Issue by dsbegnoche** [Squidex/squidex#144]
If I create a new schema, then immediately publish or try to add fields, it will throw an error.  This appears to be caused by caching in CachingSchemaProvider, and caching a null result.

Was able to fix locally by moving Cache.Set inside the null check: 
`public async Task<ISchemaEntity> FindSchemaByNameAsync(Guid appId, string name)
        {
            Guard.NotNullOrEmpty(name, nameof(name));

            var cacheKey = BuildNameCacheKey(appId, name);

            if (!Cache.TryGetValue(cacheKey, out ISchemaEntity result))
            {
                result = await repository.FindSchemaAsync(appId, name);

                if (result != null)
                {
                    Cache.Set(cacheKey, result, CacheDuration);
                    Cache.Set(BuildIdCacheKey(result.Id), result, CacheDuration);
                }
            }

            if (result != null && result.IsDeleted)
            {
                result = null;
            }

            return result;
        }

Did not make a PR though, as the first Cache.Set is outside the null check in several locations in the Caching layer, so it would seem that more than this one issue could exists?`

**Comment by SebastianStehle** [comment]
I am Not sure if it is related because write opetations should not hit the cache. Only reads

**Comment by dsbegnoche** [comment]
I am getting a 404 when due to the lookup in EnrichWithSchemaIdCommandMiddleware and a null value being cached from Schema creation.

**Comment by SebastianStehle** [comment]
The error is that the cache is not invalidated after a schema is created. Going to fix that :)
