### ISSUE TITLE
Understanding Deployment to IIS

### ISSUE THREAD

**Issue by Riddeller** [Squidex/squidex#153]
Hi,

I am currently reading the docs and trying to get Squidex up and running using IIS and docker. I've never really used docker so this is a bit of an experience for me.

I'm trying to understand the steps I need to take to go from building Squidex to the actual deployment.

NOTE: I've got MongoDB setup on the server with a database running.

Here is what I've got:

1. Run `docker build squidex/squidex:latest`  -> Outputs `publish` folder
2. Add `New Website` in IIS and point the instance to the `publish` folder
3. Change the runtime variables for MongoDB and so fourth.
4. Start IIS Website with Application Pool using the [.Net Core Hosting](https://docs.microsoft.com/en-us/aspnet/core/publishing/iis?tabs=aspnetcore2x). 

If anyone could help clarify what I need to do to get this working I'd greatly appreciate it. I understand the docker technology I just don't understand what it's used for in the context of Squidex.

**Comment by SebastianStehle** [comment]
In this case docker id only used for the build, Not for your deployment

**Comment by Riddeller** [comment]
@SebastianStehle Okay. So building with docker am I doing it right with pulling latest then hosting the whole publish folder ? Because inside the public folder there is wwwroot which is just an angular app.

**Comment by SebastianStehle** [comment]
Sorry, for the short answer, I was on my mobile phone yesterday evening.

Yes, Docker is used for Building and Deployment (if you want). But you can also build with Visual Studio, but this requires more steps. Have a look to the docker file, it is just 5 or 6 commands and should be easy to understand.

**Comment by SebastianStehle** [comment]
Closed due to inactivity. Feel free to reopen it.
