### ISSUE TITLE
Can't authenticate against API

### ISSUE THREAD

**Issue by thewebchameleon** [Squidex/squidex#156]
Hi there

Not sure why but I keep getting a 404 response from the authenticate API

my request matches what is on the swagger docs and i have tried with RESTSharp, Postman and a random [online tester](https://resttesttest.com/)

Any ideas?

**Comment by SebastianStehle** [comment]
Have you tried removing the trailing slash: https://github.com/IdentityServer/IdentityServer4/issues/1676

**Comment by thewebchameleon** [comment]
now i'm getting a 400 bad request... still investigating

**Comment by SebastianStehle** [comment]
Does it work with the UI?

**Comment by thewebchameleon** [comment]
![image](https://user-images.githubusercontent.com/16325369/32132761-bc4389bc-bbc9-11e7-9c85-d960fbf63c10.png)

**Comment by thewebchameleon** [comment]
ok got it working, created a new client to test it and got that confused

**Comment by thewebchameleon** [comment]
the solution was to remove the trailing '/' from the uri. Thanks for the help!

**Comment by SebastianStehle** [comment]
Super annoying from Identity Server 4, you are already the 10th or so reporting this to me.

**Comment by BoasE** [comment]
Can confirm this. Had some issue and removing the slash worked
