### ISSUE TITLE
Add a non contributor that currently has no squidex account

### ISSUE THREAD

**Issue by Gentlehag** [Squidex/squidex#16]
I want to add a user that doesnt not have squidex account currently.It seems like this doesnt work. So he has to create a account first. 

a) a hint text that tells me that i can only add users with a squidex account would be nice

b)It would be faster and easier if I can just type a mail and if the user doesn't have a account he gets an invitation link.

c) another down side if this dropdown shows me all current user is that I can spy the list of all user accounts ;) Maybe the list should be limitited to accounts with the same domain (if it is a custom domain)

**Comment by SebastianStehle** [comment]
I don't see a problem with c), see Github ;)
