### ISSUE TITLE
Ability to change the page titles [Enhancement]

### ISSUE THREAD

**Issue by Riddeller** [Squidex/squidex#160]
It would be nice to see a feature where you can change the page title from Squidex. This will be useful because when self-hosted in real world situation I'd like to be able to control what's being seen and to keep brand consistency.

**Comment by SebastianStehle** [comment]
You mean the <title> Attribute for tabs?

**Comment by Riddeller** [comment]
@SebastianStehle Correct. Dynamically chaning `<title>` attribute
