### ISSUE TITLE
ToCamelCase: The string length need to be checked here.

### ISSUE THREAD

**Issue by maooson** [Squidex/squidex#162]
https://github.com/Squidex/squidex/blob/bc1859a60270005a3a4269e83bb0124761e2f0f3/src/Squidex.Infrastructure/StringExtensions.cs#L336

The string length need to be checked here. May be like this^_^
```csharp
if (value.Length < 2)
{
  return value.ToLower();
}
else
{
  return char.ToLower(value[0]) + value.Substring(1);
}
```

**Comment by SebastianStehle** [comment]
Can you create a PR for it with a test in the corresponding class?
