### ISSUE TITLE
Webhook Events Missing with Rules Implementation

### ISSUE THREAD

**Issue by dsbegnoche** [Squidex/squidex#165]
With the new changes to move webhooks to rule triggers, Webhooks events are lost.  The WebhookCreatedEvent for instance errors in EventConsumerActor.cs and is caught and logged as an oldEventFound.

Should a IMigratedEvent be made to convert old webhook's to a rule with a webhook event?  If this is the route needed I can implement, just was uncertain if the missing migration was intentional or not?

**Comment by SebastianStehle** [comment]
Do you have the current version? I have fixed it on Monday.

**Comment by dsbegnoche** [comment]
Yes, working out of master I was able to reproduce an existing webhook not migrated to a rule.  Are you referring to this commit, as it seems to be only catching that event is missing? https://github.com/Squidex/squidex/commit/46f80f05b27e0ed3a2c07086bccd72fce2c5132f?diff=unified

**Comment by SebastianStehle** [comment]
Oh, this is on purpose. Actually we had so few webhooks that I thought it is not worth it to migrate it. But if you find an easy way to migrate them you are very welcome :)

**Comment by dsbegnoche** [comment]
That makes sense. We are in the same boat, only a few webhooks used for testing purposes, and no real need to migrate. Just wanted to make sure I was not missing anything.  Thanks!
