### ISSUE TITLE
Permission null when click Squidex Icon from All Apps

### ISSUE THREAD

**Issue by dsbegnoche** [Squidex/squidex#166]
When inside of an app, clicking on the Squidex Icon to return to all apps throws a JS error: Cannot read property 'permission' of null, in left-menu-component.html.  This is caused by ctx.app being null.  Was able to fix this by reverting view to reference permission property in typescript that is set on ngOnInit().

This uncovers another null reference on the Dashboard under the same scenario. This is caused by the subscription to ctx.appChanges in dashboard-page.component.ts firing and the app being null.  The only way that I was able to resolve this was to unsubscribe from the ctx.appChanges. However, this does not feel like the proper solution?

I can create a PR with the fixes I have, but wanted feedback first as unsure if resolution is the proper fix.

**Comment by SebastianStehle** [comment]
Thank you. I think the proper fix would be not to listen to the first app in the AppContext, not to all changes.
