### ISSUE TITLE
Event Consumer Issues

### ISSUE THREAD

**Issue by kwyss88** [Squidex/squidex#168]
With the recent updates to the way Event Consumers are initialized without using Autofac I can't get certain consumers to show up on the `/app/administration/event-consumers` page.

The first issue I noticed is the way the `EventConsumerActor` is configured in the `EventStoreServices.cs`. Currently it is registered like `services.AddSingleton<EventConsumerActor>()` when it should be `services.AddTransient<EventConsumerActor>()`.

After fixing that, I am still having issues with event consumers using `IAppEventConsumer` and `IAssetEventConsumer` interfaces. The only consumers that work correctly are implementing `IEventConsumer` directly or the  `ISchemaEventConsumer` interface. 

Please advise on how to fix. Thank you for the help.

**Comment by SebastianStehle** [comment]
Shit, I have no spontanous idea and will have a look.
