### ISSUE TITLE
Changing a contributor to developer form editor throws error

### ISSUE THREAD

**Issue by Gentlehag** [Squidex/squidex#17]
I want to the the role of a freshly added developer but as a result i get the error message that he already exists.

When pressing F5 (2 minutes later) he still doesnt have the new role

![image](https://cloud.githubusercontent.com/assets/4619513/25169761/7c5dec20-24e8-11e7-9b11-59aeb4df748a.png)

**Comment by SebastianStehle** [comment]
It is solved now, to be honest, I don't know why, but I have not seen any caching issues for a while :D
