### ISSUE TITLE
App removed from your SAAS

### ISSUE THREAD

**Issue by LodeKennes** [Squidex/squidex#176]
Not sure if I should post this issue here as it has nothing to do with self-hosting Squidex.

I've recently started using SquidEX Cloud and my app was removed!
The name of the app was "lombaerts". Could you please look into it?

**Comment by SebastianStehle** [comment]
It is fine :) ... I am already working on

**Comment by LodeKennes** [comment]
Alright, no problem! Thank you for the quick reply.

**Comment by LodeKennes** [comment]
Any clue as to how long it's going to take to get things sorted out?

**Comment by SebastianStehle** [comment]
Fixed

**Comment by SebastianStehle** [comment]
Sorry, the build process is a little bit too long
