### ISSUE TITLE
api PING endpoint, strange way of use?

### ISSUE THREAD

**Issue by dkeulen** [Squidex/squidex#178]
Hi,

First of all, thanks for looking into the api ping endpoint permission problems.
Secondly, now that it is working i find the way it works is kind of strange.

How i understand it, is that the ping endpoint is there to tell you if you app/api is reachable/up/listening (from the docs).
Yet to be able to ping my app/api to see if it is reachable/up/listening, i first need an auth token from/via my app/api that has to be reachable in the first place?

Unless i am misunderstanding the way apps/api and the ping for it are ment to be used OR the ping/app and token/app auth are separated reachable, shouldn't the ping endpoint be usable without authentication, so that i can see that my app/api is running, and from there continue with getting the token and do my data requests (anyways, that is wat i am trying to achieve as a service)?

**Comment by SebastianStehle** [comment]
I can make a general ping point also, just api/ping ... but I don't want that the ping endpoint can be used to check which apps exist.

**Comment by dkeulen** [comment]
Alright, i can see your point now.
But when i see that the endpoint returns 401, wont i know that the app exists as well?

**Comment by SebastianStehle** [comment]
I also return a 404 if you do not have permissions at all ;)

**Comment by SebastianStehle** [comment]
https://github.com/Squidex/squidex/blob/master/src/Squidex/Pipeline/AppPermissionAttribute.cs

**Comment by SebastianStehle** [comment]
Can I close the issue?

**Comment by dkeulen** [comment]
Hi, since the ping endpoint needs auth anyways, i have tried a different approach.
This can be closed.

**Comment by SebastianStehle** [comment]
Okay, I could also make another endpoint. If you want to know if the API itself is available.
