### ISSUE TITLE
GraphQL: Query variables not supported?

### ISSUE THREAD

**Issue by pushrbx** [Squidex/squidex#179]
Consider the following graphql query:
```graphql
query NodeSearchQuery($limit: Int!) {
    queryNodeContents(top: $limit) {
        id
        data {
            title { iv }
            slug { iv }
            type { iv }
        }
    }
}
```
Variables:
```json
{
   "limit": 25
}
```
The server returns 400 bad request. Is this an expected behavior?

Of course this query works:
```graphql
query NodeSearchQuery {
    queryNodeContents(top: 20) {
        id
        data {
            title { iv }
            slug { iv }
            type { iv }
        }
    }
}
```

**Comment by SebastianStehle** [comment]
To be honest: I never tried it. Might be a limitation of the library I use. I will check it.

**Comment by pushrbx** [comment]
https://github.com/graphql-dotnet/graphql-dotnet/issues/463#issuecomment-339878469
It seems the Variables property should be JObject instead of string. The graphql client on the admin panel is sending the variables as a json object instead of string as well.
I've tested this with Postman. This works:
```json
{
    "query": "query NodeSearchQuery($limit: Int!) {\n    queryNodeContents(top: $limit) {\n        id\n        data {\n            title { iv }\n            englishTitle { iv }\n            originalTitle { iv }\n            slug { iv }\n            slugId { iv }\n            type { iv }\n            mediaType { iv }\n            dsBeginDate { iv }\n            dsFinishDate { iv }\n            dsLength { iv }\n        }\n    }\n}",
    "variables": "{\"limit\":20}",
    "operationName": "NodeSearchQuery"
}
```
But this one doesn't:
```json
{
    "query": "query NodeSearchQuery($limit: Int!) {\n    queryNodeContents(top: $limit) {\n        id\n        data {\n            title { iv }\n            englishTitle { iv }\n            originalTitle { iv }\n            slug { iv }\n            slugId { iv }\n            type { iv }\n            mediaType { iv }\n            dsBeginDate { iv }\n            dsFinishDate { iv }\n            dsLength { iv }\n        }\n    }\n}",
    "variables": {
        "limit": 20
    },
    "operationName": "NodeSearchQuery"
}
```

So the solution can be some sort of check if the Variables property is a string or a json object, because different clients are sending this differently.

**Comment by SebastianStehle** [comment]
Is it not the up to the graphql-dotnet team to fix it?

**Comment by pushrbx** [comment]
Not sure. The lib supports both variations. Currently in squidex the Variables property is string:
```cs
namespace Squidex.Domain.Apps.Read.Contents.GraphQL
{
    public class GraphQLQuery
    {
        public string OperationName { get; set; }

        public string NamedQuery { get; set; }

        public string Query { get; set; }

        public string Variables { get; set; }
    }
}
```
Are you thinking that the GraphQL lib should force you to use a specific type?

**Comment by SebastianStehle** [comment]
Then it should be a JToken I guess.

**Comment by SebastianStehle** [comment]
Do you have an example where you can try it out?

**Comment by pushrbx** [comment]
I'm not sure what you mean. I haven't implemented this yet, I was only testing this with postman on cloud.squidex.io and on my local instance.
You can use my test app:
https://cloud.squidex.io/api/content/networkrail/graphql
Payload:
```json
{"query":"query TestQuery($limit: Int!)\n{\n  queryDefectContents(top: $limit)\n  {\n    id,\n    data {\n      width { iv }\n    }\n  }\n}","variables":{"limit":15},"operationName":"TestQuery"}
```
I've already added you as owner.

**Comment by SebastianStehle** [comment]
Thank you. I can just clone the db to my machine :)

**Comment by SebastianStehle** [comment]
The task is completed in the "Orleans" branch which will be merged and released within this week.
