### ISSUE TITLE
Content not saved

### ISSUE THREAD

**Issue by Gentlehag** [Squidex/squidex#18]
I creatd a simple schema  then i added first content element it seems like it is saved with out content i entered

![image](https://cloud.githubusercontent.com/assets/4619513/25170064/7f2cdf14-24e9-11e7-8cbc-fadd82105c8f.png)

the created schema looksl like

![image](https://cloud.githubusercontent.com/assets/4619513/25170085/97c0e1ba-24e9-11e7-9692-986fc2072092.png)

**Comment by SebastianStehle** [comment]
UI / API Problem: http://stackoverflow.com/questions/24143149/keep-casing-when-serializing-dictionaries
