### ISSUE TITLE
Cannot load the login page

### ISSUE THREAD

**Issue by frankglv** [Squidex/squidex#183]
Hi there,

I have installed Squidex into Docker. Everything seems to work smoothly, but when I try to connect via browser the page cannot load. I can see this in the console:

`squidex_proxy_1    | nginx.1    | _ {MY IP} - - [21/Nov/2017:21:41:48 +0000] "\x16\x03\x01\x00\xAE\x01\x00\x00\xAA\x03\x03\x13\x1D\x0E\xDC\xA9$\xA6J\x96\xAB\xA4\xC9\x95\x81K2\x19%\xA5@\xC8F\x9E/\xD2C\x9E\xA9e:9\xA3\x00\x00\x1C\x1A\x1A\xC0+\xC0/\xC0,\xC00\xCC\xA9\xCC\xA8\xC0\x13\xC0\x14\x00\x9C\x00\x9D\x00/\x005\x00" 400 173 "-" "-"`

What's happening here?

Thank you

**Comment by SebastianStehle** [comment]
Hi Frank,
how have you installed it? Have you used the docker-compose file?

**Comment by frankglv** [comment]
Hi Seb!

I have created the issue on GitHub.
I have just created a .env file (with the IP, mail e password settings) and
run the docker-compose script on a brand new VM (previously I pulled the
docker image but it seems it's not necessary).
The script goes well and it says it's listening on port 80 (so it should be
ok).

Tnx

2017-11-22 9:52 GMT+01:00 Sebastian Stehle <notifications@github.com>:

**Comment by SebastianStehle** [comment]
Is it this docker-compose file: https://github.com/Squidex/squidex-docker/blob/master/standalone/docker-compose.yml?

What do you mean with IP address? It must be a publicly available domain. The setup issues a certificate for it with LetsEncrypt.
