### ISSUE TITLE
[OL] Long schema display name causes edit button to overflow.

### ISSUE THREAD

**Issue by Riddeller** [Squidex/squidex#184]
As you can see below once you've added long display name you can no longer edit title again. Major UX fail 👍 

[![Bug GIF](https://i.gyazo.com/4e94a9fee07a315c24753dba6913d406.gif)](https://i.gyazo.com/4e94a9fee07a315c24753dba6913d406.mp4)

**Comment by SebastianStehle** [comment]
Thank you, thats stupid :D

**Comment by SebastianStehle** [comment]
I think I will also give the schema screen more space. 20% or so.
