### ISSUE TITLE
Restrictions for Asset fields

### ISSUE THREAD

**Issue by SebastianStehle** [Squidex/squidex#185]
Requested by @Riddeller

It should be possible to restrict what kind of assets can be uploaded.

* Maximum file size
* Maximum and minimum image size
* File type
* Define the asset folder.

**Comment by dsbegnoche** [comment]
Would this be on a per app basis, or apply to the application as a whole?

**Comment by SebastianStehle** [comment]
It would be per field.

**Comment by SebastianStehle** [comment]
Only on the Api level so far, but see: https://github.com/Squidex/squidex/pull/200
