### ISSUE TITLE
Show a visual que when editing old data from history

### ISSUE THREAD

**Issue by Riddeller** [Squidex/squidex#188]
A visual response to when you click `Load This Version` in the history window. It should show the user:
- Changes Owner
- Changes Date

Example would be the image below. 

![Visual Editing Que of old data](https://i.imgur.com/vzMu8iy.png)

My experience is that it's not clear when you're editing old data. It's just nice UX to know I'm looking at X persons changes and how old that was inside the editing window.

**Comment by SebastianStehle** [comment]
Makes sense, thank you very much.
