### ISSUE TITLE
Rules not saving on Cloud

### ISSUE THREAD

**Issue by LodeKennes** [Squidex/squidex#201]
Hi

After creating a rule on SquidEx Cloud and clicking save, it doesn't get actually saved. As soon as I refresh the page the rule is gone, could you look into this?

Thanks

**Comment by SebastianStehle** [comment]
Of course. THank you for the report.

**Comment by SebastianStehle** [comment]
Can you check it again?

**Comment by LodeKennes** [comment]
Rules still aren't being saved.

**Comment by SebastianStehle** [comment]
Do you have you app name for me?

**Comment by LodeKennes** [comment]
The app name is mcup.

**Comment by SebastianStehle** [comment]
Thank you. I will deploy it tomorrow. I could reproduce it and fix it but I want to test it more.
