### ISSUE TITLE
Squidex Cloud showing content of other users

### ISSUE THREAD

**Issue by LodeKennes** [Squidex/squidex#207]
Hi

My application in SquidEx Cloud is broken because it shows data of other users. Could you check on that please?

Application: lombaerts.

Thanks in advance!

**Comment by SebastianStehle** [comment]
Of course.

**Comment by SebastianStehle** [comment]
What kind of data?

**Comment by LodeKennes** [comment]
My content, I just checked and everything's fine again. Did you do anything or did it resolve by itself?

**Comment by SebastianStehle** [comment]
I deployed an old version temporarily.

**Comment by LodeKennes** [comment]
Alright, what do you mean by 'what kind of data'? If you still need the info.

**Comment by SebastianStehle** [comment]
No, it picked the wrong schema. Another user had a schema with the same name.-

**Comment by LodeKennes** [comment]
Alright thanks for the help, keep up the great work!
