### ISSUE TITLE
[Question] What if we want to change mongodb?

### ISSUE THREAD

**Issue by mjhpour** [Squidex/squidex#211]
Did we have to completely rewrite  `Domain.Apps.MongoDb` and `Squidex.Infrastructure.MongoDb`?

**Comment by SebastianStehle** [comment]
Basically yes. And there is also the Identity part, but we just use ASP.NET Identity and there are many solutions for that. For SQL I would use YesSql: https://github.com/sebastienros/yessql

If we would want to support many storage solutions, we probably need a better abstraction, but we would have to see first, what code the different implementations share.

**Comment by ctolkien** [comment]
I'll say too - the dependency on Mongo rules this out for us as well. No one on the team has any confidence in it.

**Comment by SebastianStehle** [comment]
What would you use? SQL Server?

**Comment by SebastianStehle** [comment]
SQL will be interesting. Because you have to create and delete tables and columns then. The question is: How to do it in the current infrastrastructure, because you have to listen to events then? e.g. 

* SchemaAdded => Create Table
* FieldAdded => Create Column
* FIeldRemoved => Remove Column
* SchemaDeleted => Delete Table

**Comment by ctolkien** [comment]
>What would you use? SQL Server?

For us specifically, given that we are now exclusively on Azure - we'd want a "cloud native" (ick) database offering. SQL Azure (and therefor also regular SQL Server) / Cosmo / Table Storage would be viable options. For .NET devs, SQL Server is probably the most familiar option I would think.

>If we would want to support many storage solutions,

Am yet to see that work out well with trying to abstract out fundamentally different stores (i.e trying to have an abstraction which works well across relational and non-relational stores).

I'm also aware that relational DB's are really not all that well suited to CMS style applications. Most that I've seen end up implementing an EAV style pattern. A DocDB makes a lot of sense in this case. We just won't touch mongo.

I have no answers, sorry... :)

**Comment by pushrbx** [comment]
CosmosDB is ok as long as you use geteventstore as event store.
However the most cloud native solution with squidex for azure would be ACS in my opinion.
I was considering once to implement azure event hub for squidex but it's just too expensive.

**Comment by SebastianStehle** [comment]
ACS?

For the EventStore I could make a SQL implementation. Should not take more than 1 or 2 days.

**Comment by pushrbx** [comment]
ACS -> Azure Container Services
