### ISSUE TITLE
[Question] How to create relation between sachems?

### ISSUE THREAD

**Issue by mjhpour** [Squidex/squidex#213]
How can we create a relationship between two or more schemes? for example how to create a product that belongs to some category.

imagine that we want to create `Product Contents` which are related to a `Category Content`. is there anything like foreign keys in SQL or something like that?

**Comment by SebastianStehle** [comment]
Have you checked the References field?

**Comment by mjhpour** [comment]
Not completely. just right to the `ARCHITECTURE` section. Sorry.  I think that you handle it with 

```
$filter

The $filter system query option allows clients to filter a collection of resources that are addressed by a request URL.
```

right?

**Comment by mjhpour** [comment]
Documentation exists in the Reference field.
