### ISSUE TITLE
External system check should happen before migration

### ISSUE THREAD

**Issue by pushrbx** [Squidex/squidex#215]
I'm using GetEventStore and the migration tries to run GetEventsAsync function, but it throws an exception `System.InvalidOperationException: EventStoreConnection 'ES-52bd9eec-4649-4669-b352-bcc651 cf1686' is not active`. (see pr #214 )

After swapping the order it works fine (WebStartup.cs):
```cs
public void Configure(IApplicationBuilder app)
{
    app.ApplicationServices.LogConfiguration();
    app.ApplicationServices.TestExternalSystems();
    app.ApplicationServices.Migrate();

    app.UseMyCors();
    app.UseMyForwardingRules();
    app.UseMyTracking();

    app.ConfigureApi();
    app.ConfigurePortal();
    app.ConfigureIdentityServer();

    app.ConfigureFrontend();
}
```

**Comment by SebastianStehle** [comment]
But then we need another interface also. At the moment the IExternalSystem interface is used to start all kind of processes. And they must start after the migration. Therefore we need something like "IRunnable" or so.

**Comment by pushrbx** [comment]
What if the `IExternalSystem` would have a readonly property called `bool MustConnectBeforeMigration` and the `TestExternalSystems` extension method would filter based on that property. I think they know the same thing: test them selves, so they are not different from each other thus we shouldn't distinguish them with different interfaces.

**Comment by SebastianStehle** [comment]
I already changed it to my IRunnable interface before I read your comment.
