### ISSUE TITLE
Azure AD support

### ISSUE THREAD

**Issue by spacecat** [Squidex/squidex#223]
Just wondering if Squidex can be integrated with Azure AD?

**Comment by SebastianStehle** [comment]
Hi @spacecat

We use IdentityServer 4 for authentication. And I have seen samples that added azure AD as external authentication provider. So it seems to be possible, but you have to extend the code for it. It should not be that hard. Would be awesome to get an PR for that :)

**Comment by spacecat** [comment]
It would be nice indeed. We'll see if we get resources for it and if the budget allows it and if it will part of the final requirements.

**Comment by SebastianStehle** [comment]
Are you planing to invest time in this feature?

**Comment by spacecat** [comment]
I wish I could but at the moment I can't. Hopefully in the future or if someone else could take on the challenge that would be great too.
