### ISSUE TITLE
[UI] No dropdown for client permissions

### ISSUE THREAD

**Issue by pushrbx** [Squidex/squidex#227]
It should look like this:
![image234234](https://user-images.githubusercontent.com/6832715/35187482-3e01d4d8-fe1c-11e7-9415-18b17295d5a1.png)
    
But it looks like this:
![screenshot_20180120-173934](https://user-images.githubusercontent.com/6832715/35187484-52e0c210-fe1c-11e7-8760-73db61f627fb.png)

Browser: Firefox 57.0.4 (64-bit)

**Comment by mjhpour** [comment]
Same here.

**Comment by SebastianStehle** [comment]
Sorry, this was a super stupid copy and paste error. I will fix it as soon as possible.

**Comment by SebastianStehle** [comment]
Will be released to cloud in ~1 h
