### ISSUE TITLE
Getting images from assets

### ISSUE THREAD

**Issue by stefan12r** [Squidex/squidex#229]
I'm wondering if you could help me with this:
I have some content which has a property of Asset type. Is it possible to get an image with content when I'm getting it instead of the Asset's ID? Also how to get an image from Assets when I have it's ID, because in the response body from the API call, I don't see any image data, just image information.

**Comment by SebastianStehle** [comment]
Hi Stefan,

I hope this helps: https://cloud.squidex.io/api/docs#operation/AssetContent_GetAssetContent

**Comment by stefan12r** [comment]
Yes, that helped a lot! I really appreciate your answer!

**Comment by SebastianStehle** [comment]
I am about to write a documentation for that

**Comment by SebastianStehle** [comment]
Started with some stuff: https://docs.squidex.io/04-guides/05-assets.html
