### ISSUE TITLE
Getting referenced content

### ISSUE THREAD

**Issue by stefan12r** [Squidex/squidex#230]
I have a schema that has a reference filed for another schema, is it possible to get the referenced schema's content as part of the response data? Currently I am getting only the reference schema's id so I need to make another call to get that content.

**Comment by SebastianStehle** [comment]
Not with REST, but you could play around with graphql.

**Comment by SebastianStehle** [comment]
Go to API -> GraphQL to get the integrated GraphiQL query editor. You can also retrieve assets directly.

**Comment by stefan12r** [comment]
Thank you very much!
