### ISSUE TITLE
How to target Squidex's GraphQL

### ISSUE THREAD

**Issue by stefan12r** [Squidex/squidex#234]
A stupid question : 
How to target Squidex GraphQL API, using Postman or Insomnia.
I have tried both via GET and POST requests but can't seem to get it to work. When I try executing a query via GET i get a response saying that the request has succeeded but i don't get the expected result, instead I get something like "Loading Squidex".
Thank you in advance!

**Comment by SebastianStehle** [comment]
What endpoint do you use? It is `api/content/{app}/graphql/`

**Comment by stefan12r** [comment]
Yes

**Comment by stefan12r** [comment]
Aaah yes, I didn't read your response correctly. That endpoint works just fine. 
Thank you very much! You're a real lifesaver!
