### ISSUE TITLE
[Request] Schema Categories

### ISSUE THREAD

**Issue by Riddeller** [Squidex/squidex#245]
I think a nice feature would be to have the ability to group schemas in 'folders'.

If you're looking to do a installation of Squidex with multiple purposes you end up with lots of schemas in one scroll. 

Just having the ability to have visual only folders would be a nice addition. You could structure items in like so e.g.

Schemas (Default Folder)
-> Schema
-> Schema...

Custom Folder
-> Schema
-> Schema...

Blog (Folder)
-> PostSchema
-> SlugSchema
-> CategorySchema

Custom Folder
-> Schema
-> Schema...

**Comment by SebastianStehle** [comment]
True, but why are you not creating multiple apps?

**Comment by Riddeller** [comment]
@SebastianStehle, It's technically not a different app but a branch of my app.

**Comment by SebastianStehle** [comment]
Okay, just wanted to understand it. Has already been requested several times :)

**Comment by Riddeller** [comment]
@SebastianStehle, I personally think it's just more user friendly and better user experience to organize using folders as it can make it less crazy for people using squidex that's not a developer... Yeah feel free to close the ticket if it's on the radar. 👍

**Comment by SebastianStehle** [comment]
Depends on the use case I would day. The apps are already an organizational unit, where you can give permissions and so on. If you need that you can go with multiple apps, e.g. for different domains / bounded contexts.

But even within an app, there should be a way to group them. That's right. I am open for PR's. I would just make a "Category" field on the schema and let the UI handle it.

**Comment by SebastianStehle** [comment]
https://trello.com/c/oNY4JjnS/40-groups-for-schemas
