### ISSUE TITLE
Cannot select schema for reference fields

### ISSUE THREAD

**Issue by Might-E** [Squidex/squidex#246]
I am using squidex cloud and made some schemas. After creating a reference field I could not figure out how they worked at first but at some point I found that you could select a schema where you reference the content.

So I did that and then tried to do it again for another field but I can't find the option to select the schema for a reference field anywhere. In the end I used the import feature to manually set the reference schema GUID, which worked.

So I am guessing that in some (or most) cases the referencing schema selection doesn't show up. 
The thing is that I don't remember exactly where I was able to select te schema the first time.

![squidex-reference-1](https://user-images.githubusercontent.com/17081164/35966936-9ecd769e-0cbf-11e8-86b9-626958d23c41.PNG)
![squidex-reference-2](https://user-images.githubusercontent.com/17081164/35966937-9ee9614c-0cbf-11e8-9f5c-e6dc3e39c88f.PNG)
![squidex-reference-3](https://user-images.githubusercontent.com/17081164/35966938-9f009a2e-0cbf-11e8-8f66-edbc3691020b.PNG)

**Comment by SebastianStehle** [comment]
I fixed the styling and accidently removed this. I am already on it. Will be out in ~60 min.

**Comment by Might-E** [comment]
Wow that's a quick reply 👍 
Thanks, I thought I was going insane because I was trying squidex for the first time, checking if it could work for us.

**Comment by SebastianStehle** [comment]
Fixed.

**Comment by SebastianStehle** [comment]
Thanks for your report, more feedback is very welcome. You can also join our slack if you want.
