### ISSUE TITLE
[Request] Traffic / Quota per client

### ISSUE THREAD

**Issue by BoasE** [Squidex/squidex#255]
When we have a issue when a client creates to many requests it would very helpful to see in squidex which client es creating how much traffic.

also it would be nice to see more then the given time range

**Comment by SebastianStehle** [comment]
Good point. We are improving the subscription management at the moment to decouple subscriptions from apps and will add it then.

What do you mean with "more"? Flexible time range?

**Comment by SebastianStehle** [comment]
https://trello.com/c/gVaGvZhv/81-traffic-quote-per-client
