### ISSUE TITLE
405 When updating Schema 

### ISSUE THREAD

**Issue by shiggan** [Squidex/squidex#258]
I have a version built from 782c351 (Global.json removed; Mar 5, 2018)

When I try to update any schema I get a 405 error

Request

PUT: http://.../api/apps/sample-blog/schemas/posts/fields/1
Host: ...
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0
Accept: application/json, text/plain, */*
Accept-Language: *
Accept-Encoding: gzip, deflate
Referer: http://.../app/sample-blog/schemas/posts
If-Match: 1
Authorization: Bearer .....
Pragma: no-cache
Content-Type: application/json
Content-Length: 265
DNT: 1
Connection: keep-alive
Request Body : {"properties":{"fieldType":"String","label":"Title","hints":"ss","placeholder":null,"isRequired":true,"isListField":true,"inlineEditable":null,"editor":"Input","defaultValue":null,"pattern":null,"patternMessage":null,"minLength":null,"maxLength":100}}

Response

Allow: GET, HEAD, OPTIONS, TRACE
Content-Type: text/html
Server: Microsoft-IIS/10.0
X-Powered-By: ASP.NET
Date: Sat, 10 Mar 2018 04:46:53 GMT
Content-Length: 1293

Status Code 405

We do get a response body back which just says
```html
... snip bunch of html
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>405 - HTTP verb used to access this page is not allowed.</h2>
  <h3>The page you are looking for cannot be displayed because an invalid method (HTTP verb) was used to attempt access.</h3>
 </fieldset></div>
</div>
```

**Comment by SebastianStehle** [comment]
Are you hosting with IIS? Is WebDEV installed?

**Comment by shiggan** [comment]
Hosted in IIS; and I am using the schema designer ui rather than the management api directly (not sure if that was clear).

Not quite certian what you mean by WebDEV being installed.

**Comment by SebastianStehle** [comment]
WebDAV is an IIS component. The error above comes from IIS I think and I have seen it when WebDAV is installed (e.g. when you check every checkbox when installing IIS).

https://stackoverflow.com/questions/6147181/405-method-not-allowed-in-iis7-5-for-put-method

**Comment by SebastianStehle** [comment]
Sorry, DAV, not DEV :D

**Comment by shiggan** [comment]
Oh wow; that will teach me for not looking properly at IIS; thanks heaps :)
