### ISSUE TITLE
API call from javascript

### ISSUE THREAD

**Issue by LucaGabi** [Squidex/squidex#265]
How to deal with language property in js environment ?? It seams an overhead.. (when using vuejs always put iv ..)

**Comment by SebastianStehle** [comment]
You can easily write a helper function in your api layer, something like

	const convertData = (entity) => {
		const result = {...entity};
		
		for (let key in entity.data) {
			const value = entity.data[value];
			
			if (value.iv) {
				result.data[key] = value.iv;
			] else {
				result.data[key] = value;
			}
		}
	};

**Comment by LucaGabi** [comment]
Thanks, this works but still I would have proffered a clean json data from the request.. Maybe the language could have been placed in the URL as a query parameter.. and fallback to default language where no translation for a field value. 

For the specific cases .. mentioned in the docs, I think this should be the responsibility of the actual API being designed ..

Thanks anyway.

**Comment by SebastianStehle** [comment]
Totally agree.
