### ISSUE TITLE
UI Shadows 

### ISSUE THREAD

**Issue by LucaGabi** [Squidex/squidex#266]
Hi,

    Just an opinion: add shadows to elements and panels to show order of panels and slides?
(and css scrollbars in chrome :) )

![squdexuishadowsscroll](https://user-images.githubusercontent.com/37976898/38203010-6c2a29f6-36a6-11e8-9552-eeaf689b019c.png)

**Comment by SebastianStehle** [comment]
Thank you. We tested it months ago out and it looked bad ;)

But it is very likely that we will move away from the panels for contents and assets in the next weeks. https://medium.com/squidex/lessons-from-our-customer-survey-d60f79d8a417
