### ISSUE TITLE
Rich Text Editor Improvements

### ISSUE THREAD

**Issue by ORoberts221** [Squidex/squidex#267]
Ideally I would like some support for bulleted lists within the rich text editor, currently the string rich text editor does support unordered lists if you manually type out the html in the source code, however there is no easy option to do this via the editor options. 

As I plan to have some non-technical users (which is also why I'm avoiding the markdown option) this would be a big help.

Unsure if I should make a separate issue for this, but the ability to customise the editor options by toggling them on or off would also be extremely useful (e.g. disabling the ability for users to add assets on some editors).

**Comment by SebastianStehle** [comment]
I will add the bulleted lists soon, probably this friday. Can you open another issue for the customization? (or a PR? ;))

**Comment by ORoberts221** [comment]
Will do, thank you!

**Comment by SebastianStehle** [comment]
Done
