### ISSUE TITLE
Track the number of API calls per day.

### ISSUE THREAD

**Issue by SebastianStehle** [Squidex/squidex#27]
* Provide store to track number.
* Show charts

**Comment by ctolkien** [comment]
Track duration of call as well?

**Comment by SebastianStehle** [comment]
Thanks for your feedback.

Good point. At the moment I use elastic search to track this kind of stuff: https://medium.com/squidex/semantic-logging-in-asp-net-core-f89038ea7dd7

I don't want to reinvent the wheel but some aggregated value should be easy to implement.

**Comment by SebastianStehle** [comment]
Done and deployed.
