### ISSUE TITLE
Impossible to drag&drop 4th images from assets on a smaller screens

### ISSUE THREAD

**Issue by EvgeniySokolov** [Squidex/squidex#270]
On my screen (13") it's impossible to select 4th image from assets in order to drop it into article. 
Here is an example: 
1) I have 4 images in my assets
2) In case I scroll screen to be able to see 4th image I won't be able to drop it into corresponding field, since 'drop' area isn't visible. 
3) There is no issue with 'drop' area for references field type, since the area is having full width of the top part of field. 

So, the fix can be using the full width on the top of the asset field area: 

<img width="1301" alt="screen shot 2018-04-12 at 14 49 02" src="https://user-images.githubusercontent.com/36033691/38678371-1ad9636a-3e61-11e8-92ea-a022d3cccd0a.png">

**Comment by SebastianStehle** [comment]
Hi, we will replace the system with modal Dialogs, hopefully next week. See our roadmap: https://trello.com/c/A5SSKVTx/66-copy-multiple-assets

**Comment by SebastianStehle** [comment]
Done
