### ISSUE TITLE
Field's value (selected for 'List View' in schema defenition) isn't displayed in content

### ISSUE THREAD

**Issue by EvgeniySokolov** [Squidex/squidex#273]
Open Content, select a schema and in the view (that list of contents) the header contains all list selected for 'List view' however non of the elements contains value: 

Exampe: Title and URL were selected as 'List View' and used to display values for the fields. 
Now they are empty. 

<img width="1216" alt="screen shot 2018-04-15 at 13 45 51" src="https://user-images.githubusercontent.com/36033691/38778090-94c19e32-40b3-11e8-8c37-92fcd998dd73.png">

**Comment by SebastianStehle** [comment]
Thx, I will have a look immediately.

**Comment by SebastianStehle** [comment]
I cannot reproduce it.

**Comment by EvgeniySokolov** [comment]
I used to play with languages last week: despite default (en) I added other language (de) and after some testing 'de' was deleted. 
At the moment I have only 1 language (en), as well as the content that I have is defined in the default language.
And the issue is presented.  

However, if I add any other language and go to Content all the title (in my case Title and URL) are displayed. 
Once I delete second language - the title are gone again.

**Comment by EvgeniySokolov** [comment]
I have some fields localized. However, all content is in 'en' only. 

As the moment we need only 1 language (en). I just tried support of the 2nd language and after some testing second language was deleted. 

Let me try to describe the bug in following way. 

Expected: 
1. There is only one language (en) for content. 
2. In the List of content fields selected with 'List View' display values. 

Actual: 
The list selected for 'List View' displayed in header, but the values of them are 'blanks'. 

Screenshots: 
1. Settings -> Languages -> only English avaible. 
2. Content -> schema-name (in our case edu-content): 

![1](https://user-images.githubusercontent.com/36033691/38801294-ba36f8b8-4169-11e8-98be-461bc386d07a.png)

3. Go to Settings -> Languages -> add one more language (e.g. German): 
![2](https://user-images.githubusercontent.com/36033691/38801353-ded7ab2c-4169-11e8-8c6f-cfa0adddfab5.png)

4. Go back to Content -> schema-name (in our case edu-content):
'en' and 'de' are available, but 'en' is selected. The header values (Title and URL) are displayed: 
 
![3](https://user-images.githubusercontent.com/36033691/38801419-0f443924-416a-11e8-976c-c90f2653f65f.png)

in case I switch language on this page to 'de' the header values are empty (since I didn't input any values for 'de' fields)

5. Settings -> Languages -> remove 'de' language 
6. Go to Content -> schema-name (in our case edu-content): Header values aren't there anymore: 

![1](https://user-images.githubusercontent.com/36033691/38801294-ba36f8b8-4169-11e8-98be-461bc386d07a.png)

**Comment by SebastianStehle** [comment]
Okay, I can reproduce it now

**Comment by SebastianStehle** [comment]
Can you try it again?

**Comment by EvgeniySokolov** [comment]
Looks good now! 
Thanks for quick fix!

**Comment by EvgeniySokolov** [comment]
Sorry for bringing this back: there is one more place where the blank values are still there. 

Steps to reproduce: 
1. Define two schemas and use a field in one of the schemas of type 'reference' to second schema. 
2. Create a content in 'referenced' schema. 
3. Start creating content in 'main' schema. On clicking 'click here to link a content' will open a popup with content from referenced schema and the values of 'List view' fields will be blank.

**Comment by SebastianStehle** [comment]
I will try to fix it today or tomorrow. I have a cold and spending my time in bed, sorry for the delay.
