### ISSUE TITLE
Is there a way to filter out draft contents

### ISSUE THREAD

**Issue by zhangpengchen** [Squidex/squidex#274]
In the graphql API we did not see a field called status to allow us filter out draft contents for front-end.

**Comment by zhangpeng-kooboo** [comment]
Hi @SebastianStehle ,
In GraphQL we also received draft contents at this moment.
![draft content](https://user-images.githubusercontent.com/4378651/38812360-6088e6b4-418c-11e8-9449-0c72fb74baff.png)
![graphql](https://user-images.githubusercontent.com/4378651/38812377-6963cf74-418c-11e8-8f97-b224012aeead.png)

**Comment by SebastianStehle** [comment]
yes, but only in the UI

**Comment by SebastianStehle** [comment]
I can add the status field

**Comment by zhangpeng-kooboo** [comment]
@SebastianStehle that would be great, most of time we are using GraphQL UI for testing :)

**Comment by SebastianStehle** [comment]
I added the status to the output: https://github.com/Squidex/squidex/commit/6ef3795ca30e76d42cb89451137fbd07fe6cc4fd

Will be deployed tomorrow
