### ISSUE TITLE
[Idea] Include contributor info into the rule formatter

### ISSUE THREAD

**Issue by OlegKuliasovMatmatch** [Squidex/squidex#275]
As a user I want to see the name of the contributor responsible for an event. I set up Slack notifications and it's working perfectly, and I can see updates, but I have no idea who did it.

**Comment by SebastianStehle** [comment]
I prefer github, especially if you have something that is easy to implement. To you have more ideas for the rule formatter? I was thinking about the url to the content.

**Comment by OlegKuliasovMatmatch** [comment]
1. There is a 'List Field' option for fields. It would be nice if data from these fields was always available as an array or just from the first field (but always), then I would use a single rule configuration for all schemas (I cannot do it now, because different schemas have different fields).
2. Published, Deleted events have no content data, so it's not clear what was removed or published.
