### ISSUE TITLE
Is there a docker image for Windows system

### ISSUE THREAD

**Issue by zhangpengchen** [Squidex/squidex#276]
Hi @SebastianStehle ,

I saw there has a docker image in https://hub.docker.com/r/squidex/squidex/ really nice.

But when I am requesting "windows", it shows me: cannot download image with operation system "linux" when requesting "windows".

Is there a docker image for Windows?

Thks,
Zhangpeng

**Comment by SebastianStehle** [comment]
I can prepare one for you. But it will take a little bit of time.

**Comment by zhangpengchen** [comment]
@SebastianStehle that is awesome 👍
