### ISSUE TITLE
Deploying on Azure (Using cosmosDB)

### ISSUE THREAD

**Issue by mmusket** [Squidex/squidex#278]
I am trying to deploy squidex on Azure, and I would like it to run off the azure mongoDB service CosmosDB. I can see that it created some of the collections but I get the exception 
`MongoCommandException: Command createIndexes failed: 'text' is not supported.`

Looks like the text index is not supported. Are there any workarounds for this? or can the schema be changed to support cosmos.

**Comment by ctolkien** [comment]
This has been discussed a few times (eg #44), basically it doesn't work as CosmosDB doesn't support all features of Mongo (some of which are currently required).
