### ISSUE TITLE
404 on content on SquidEx cloud?

### ISSUE THREAD

**Issue by LodeKennes** [Squidex/squidex#279]
Hi

For my app 'lombaerts' I get a 404 on the content for 'products'. Any reason as to why this is happening? Doesn't happen to other schema's.

Thanks

**Comment by SebastianStehle** [comment]
Where exactly?

**Comment by LodeKennes** [comment]
This url: https://cloud.squidex.io/app/lombaerts/content/products

It gives me a 404 while the other contents don't. It doesn't load through the API anymore either.

**Comment by SebastianStehle** [comment]
I will have a look.

**Comment by LodeKennes** [comment]
Thanks.

**Comment by LodeKennes** [comment]
Everything seems to be working again. You fixed it?

**Comment by SebastianStehle** [comment]
No, I have a new notebook and have to install google cloud sdk right now ;)

**Comment by LodeKennes** [comment]
Very weird. Didn't change a singe line of code and it worked again. Even in my production environment which had already been deployed and was failing like 10 minutes ago. Anyway, cheers! Enjoy the new notebook.
