### ISSUE TITLE
problem deserializing AssetItem

### ISSUE THREAD

**Issue by jojoblaze** [Squidex/squidex#284]
I have a very simple schema for my vinyls collection which has two properties: a Title (string) and a Cover (asset).
In order to test SwaggerCodeGen capabilities I generated a C# client, but when I try to retrieve data I get this error:

_Error converting value \"e221af64-a27c-4fd0-a054-7b7f40c040ce\" to type 'IO.Swagger.Model.AssetItem'. Path 'items[0].data.cover.iv[0]_

Cms is returning the image(s) ID(s) which is good, but deserialization fails.

**Comment by SebastianStehle** [comment]
Which code generator do you use?

**Comment by jojoblaze** [comment]
From Swagger Editor, Generate Client -> csharp

**Comment by SebastianStehle** [comment]
I think it is a bug in swagger generator. Check out: https://github.com/RSuter/NSwag/wiki/NSwagStudio

**Comment by jojoblaze** [comment]
I'm not sure about the AssetItem openapi definition provided by Squidex:

```
  AssetItem:
    type: string
```

I expected it was of type object with a member of type string, not a string itself (which cannot be inherited).
The definition is legit from the openapi point of view, but in the C# "translation" a class cannot "be" a string.

I'd like to share some opinion about this.

**Comment by SebastianStehle** [comment]
But the example responses/requests look good. In Redox (integrated docs) and in the Swagger Editor. And NSwag can also handle it correctly.

**Comment by jojoblaze** [comment]
Yes you are right, with NSwag the cover field is handled as correctly a collection of strings.
