### ISSUE TITLE
Assets with mode other than Max (default) return 404

### ISSUE THREAD

**Issue by ba55ie** [Squidex/squidex#288]
This works:

- https://cloud.squidex.io/api/assets/5fecd7f2-21b2-4ff2-bda9-f8135565c3ba/?width=100
- https://cloud.squidex.io/api/assets/5fecd7f2-21b2-4ff2-bda9-f8135565c3ba/?width=100&mode=Max

And this doesn't:
- https://cloud.squidex.io/api/assets/5fecd7f2-21b2-4ff2-bda9-f8135565c3ba/?width=100&mode=Pad

https://docs.squidex.io/guides/assets

Also, the [API docs](https://cloud.squidex.io/api/docs#operation/AssetContent_GetAssetContent) state that an `app` query param is required, but that doesn't seem to be the case.

**Comment by SebastianStehle** [comment]
Thx, I will have a look. The `app` URL parameter is obviously wrong. Probably a copy and paste issue.
