### ISSUE TITLE
Package Restore Failed

### ISSUE THREAD

**Issue by soyhanbeyazit** [Squidex/squidex#290]
I have cloned master but no luck with building it. Below is the package manager console output.

I am using Visual Studio for Mac Community edition

> Running non-parallel restore.
> Reading project file /Users/soyhan.beyazit/Developer/squidex/src/Squidex/Squidex.csproj.
> Restoring packages for /Users/soyhan.beyazit/Developer/squidex/src/Squidex/Squidex.csproj...
> Restoring packages for .NETCoreApp,Version=v2.0...
>   GET https://api.nuget.org/v3-flatcontainer/microsoft.orleans.server /index.json
>   GET https://dotnetmyget.blob.core.windows.net/artifacts/orleans-ci/nuget/v3/flatcontainer/microsoft.orleans.server /index.json
>   NotFound https://api.nuget.org/v3-flatcontainer/microsoft.orleans.server /index.json 840ms
>   NotFound https://dotnetmyget.blob.core.windows.net/artifacts/orleans-ci/nuget/v3/flatcontainer/microsoft.orleans.server /index.json 956ms
> Resolving conflicts for .NETCoreApp,Version=v2.0...
> Unable to find package Microsoft.Orleans.Server . No packages exist with this id in source(s): localfeed, myget.org, nuget.org
> Committing restore...
> Writing lock file to disk. Path: /Users/soyhan.beyazit/Developer/squidex/src/Squidex/obj/project.assets.json
> Writing cache file to disk. Path: /Users/soyhan.beyazit/Developer/squidex/src/Squidex/obj/Squidex.csproj.nuget.cache
> Restore failed in 4.12 sec for /Users/soyhan.beyazit/Developer/squidex/src/Squidex/Squidex.csproj.
> 
> NuGet Config files used:
>     /Users/soyhan.beyazit/Developer/squidex/nuget.config
>     /Users/soyhan.beyazit/.config/NuGet/NuGet.Config
> 
> Feeds used:
>     /Users/soyhan.beyazit/Developer/squidex/libs
>     https://api.nuget.org/v3/index.json
>     https://dotnet.myget.org/F/orleans-ci/api/v3/index.json
> Restore failed for 'Microsoft.Orleans.Server  (>= 2.0.0-rc2)'.
> Restore failed.

**Comment by SebastianStehle** [comment]
Are you using the current version? Because 2.0.0-rc2 ?

**Comment by soyhanbeyazit** [comment]
I didn't change anything on packages, I just tried to restore nuget packages.
