### ISSUE TITLE
Change Squidex Branding and Clear Database

### ISSUE THREAD

**Issue by johnhorsema** [Squidex/squidex#291]
I got Squidex up and running with Docker Compose. Now I would like to change the Squidex logo and welcome message. How can I do so?

Also, I created projects and schemas I do not use anymore. How can I 'reset' the Mongo DB to empty state?

**Comment by SebastianStehle** [comment]
I would download a Mongo Client like https://studio3t.com and delete the databases.

About logo and welcome message: Not possible yet, but a PR is welcome.

**Comment by johnhorsema** [comment]
@SebastianStehle Managed to remove the MongoDB content with the below
Is it useful to add into the documentation?
Also, still have no clue on changing the welcoming message... Any pointers?
```
docker-compose ps                            # Find the container name for MongoDB
docker exec -it <mongo-container-id> bash    # Get into the container console
mongo                                        # Get into Mongo console
use Squidex;
db.dropDatabase();
use SquidexContent;
db.dropDatabase();
```

**Comment by SebastianStehle** [comment]
Right now there is no setting to change the welcome message.

**Comment by SebastianStehle** [comment]
But there is a controller for these kind of settings: https://github.com/Squidex/squidex/blob/master/src/Squidex/Areas/Api/Controllers/UI/UIController.cs

If you want to provide a PR you are welcome, but for me the priority is relatively low at the moment. But it is part of "Allow theming for apps": https://trello.com/b/KakM4F3S/squidex-roadmap
