### ISSUE TITLE
Feature Request - Schema change undo

### ISSUE THREAD

**Issue by jakenuts** [Squidex/squidex#293]
It may be that this is already addressed, and I can't begin to fathom the amount of work you have (I'd kill for a coder at your level) but it seems quite easy to delete a schema field and thus the data stored in that field. That would be fine if there was some sort of "undo" but I haven't found it. 

Thanks!

James White

**Comment by SebastianStehle** [comment]
Actually we never delete data when you remove a field, Each field gets a unique ID that is never repeated and we use this ID for the data. As long as you do not make changes we could just recreate the field with the same ID and you have your data back.

**Comment by SebastianStehle** [comment]
I have added it to our roadmap: https://trello.com/c/o5OLgX2R/89-restore-deleted-fields Being a small task I can probably implement it next week.
