### ISSUE TITLE
The schema of mutation are lost

### ISSUE THREAD

**Issue by husheng-kooboo** [Squidex/squidex#298]
After I run the mution GraphQL,only got this message.
`{
  "errors": [
    {
      "message": "Schema is not configured for mutations"
    }
  ]
}`
Can somebody tell me how could this happen,I didn't make any change of the schema.Thanks

**Comment by SebastianStehle** [comment]
Are you using the cloud version or hosting it by yourself?

**Comment by SebastianStehle** [comment]
If you use the cloud, read this: https://medium.com/squidex/new-feature-released-nested-schemas-e2053bc69630

If you host it by yourself I would use an older version.

**Comment by husheng-kooboo** [comment]
Only me,could you tell me is there possible to check the log?

**Comment by SebastianStehle** [comment]
Only me?

**Comment by husheng-kooboo** [comment]
So you mean in the new release the mutation has been removed in the cloud version?Then if I want to use mutation again,to insert,update and delete data in the GraphQL,how am I supposed to do?Sorry,I'm just a freshmen to the Squidex.Thanks again.

**Comment by SebastianStehle** [comment]
Yes, the mutations have been removed. As a I pointed out in the blog post it was too hard to maintain them. I know that it is very controversial, but I had to make a decision.

In the API section of the UI you will find a link to the swagger documentation for the REST endpoint, which can be used to make updates. It is the same endpoint that it is used by the UI.

**Comment by husheng-kooboo** [comment]
OK.Thanks for your suggestion.I'll have a try.
