### ISSUE TITLE
Setting up Squidex on AWS without Docker

### ISSUE THREAD

**Issue by hamzasharif** [Squidex/squidex#299]
Hi,

How would I go about setting up Squidex via an AWS EC2 instance?

I'm going to set up a revere proxy in nginx pointing to the .net core Squidex published application.

Aside from that, how would I set up MongoDB?

**Comment by SebastianStehle** [comment]
Windows or Linux?

In general there is nothing special about our setup. It is a normal ASP.NET Core application. 

The installation instructions for MongoDB can be found here: https://docs.mongodb.com/manual/administration/install-on-linux/

**Comment by hamzasharif** [comment]
@SebastianStehle that's fine I was just checking, thank you.

**Comment by SebastianStehle** [comment]
My recommendation is to get a cheap server at vultr.com (https://www.vultr.com/) and then use our docker-compose scripts. If you are used to docker you can set it up within minutes.
