### ISSUE TITLE
Docker build hangs on npm install

### ISSUE THREAD

**Issue by hamzasharif** [Squidex/squidex#300]
<img width="738" alt="screen shot 2018-06-14 at 10 37 04" src="https://user-images.githubusercontent.com/30042483/41404369-ef931c20-6fbe-11e8-956a-b3d8266d7079.png">

I have an ubuntu server (16.04) set up on AWS, I have installed Docker and Docker compose. 

Following your instructions, after firing npm install it just hangs...

**Comment by pushrbx** [comment]
npm install is usually is slow. Around 8-12 minutes. Also drone is doing docker builds too:  https://build.squidex.io/Squidex/squidex/1247/3
And it is working fine.
It might be also the case of the ufw settings on your box? But this is a rough guess.
