### ISSUE TITLE
Add History feature

### ISSUE THREAD

**Issue by BoasE** [Squidex/squidex#35]
As Squidex is eventsourced it has informations about all versions of an item like "content"

so it would be nice to see the history and the values at a given state. 

From this we get some nice sourcecontroll-like features
- Revert error changes
- Having some kind of manuell tiny backup
- see when a wrong content were created and who did it.

**Comment by SebastianStehle** [comment]
One of the reasons why we use CQRS, will come sooner or later, but we need a good concept first.
