### ISSUE TITLE
Add Backup and Restore Function in the UI / API 

### ISSUE THREAD

**Issue by BoasE** [Squidex/squidex#37]
It would be nice to have a api or an ui to have general backup and restore mechanism. (Similar to wordpress?)

this will be most important for all on cloud demand users which don't have access to the physical installation

**Comment by sharepointpita** [comment]
This is a nice feature indeed. We went from Squidex Cloud to our own hosted environment. Without a export-import feature (of App level) you need to replicate schema, content etc. by hand.
