### ISSUE TITLE
ETag support for Contents

### ISSUE THREAD

**Issue by BoasE** [Squidex/squidex#40]
* Send ETag (DONE)
* Send NotModified status code if ETag matches If-Match header

**Comment by SebastianStehle** [comment]
Sorry, I don't understand it, some spell checking would be nice ;)

**Comment by SebastianStehle** [comment]
Too much risk for now with the management portal. But sooner or later we need something like that. A specialized API could help as well.

**Comment by BoasE** [comment]
Any news on this?

**Comment by SebastianStehle** [comment]
Still no priority
