### ISSUE TITLE
Copy multiple assets from the asset page to an asset field at once

### ISSUE THREAD

**Issue by sharepointpita** [Squidex/squidex#41]
> RFC

Possibility to copy multiple assets from the assets page into a Asset type field, but there is no multiple select functionality. (So that you can drag multiple assets from assets component to an asset field type)
👍

**Comment by SebastianStehle** [comment]
As soon as I find an easy solution for that I will implement it. At the moment I use https://github.com/akserg/ng2-dnd and it seems not to be planned yet: https://github.com/akserg/ng2-dnd/issues/43
