### ISSUE TITLE
Possibility to invite new users to squidex system

### ISSUE THREAD

**Issue by sharepointpita** [Squidex/squidex#43]
At the moment of writing an user must first login to the squidex system before you can unlock him and give him the right rights for a particular app. 

A more user friendly solution can be that you can invite someone by a email.  (like Slack does)
When this user then accepts the link and logs in with his google account, he can directly access the content where you gave him the rights for.

More detailed:
_Add the moment the user has been added by the admin, but the user has not clicked on the invite link already, the admin can change the rights for this "not activated" user._

**Comment by SebastianStehle** [comment]
Sounds like a reasonable point.
