### ISSUE TITLE
Problem with adding assets to WYSIWYG

### ISSUE THREAD

**Issue by kwolekgrzesiek** [Squidex/squidex#500]
I am unable to add pictures to WYSIWYG editor. 

Steps to reproduce:
1. Add new page
2. Fill title
3. Fill text and add picture (for example from assets window)
4. Click save and publish.

Result: 
![image](https://user-images.githubusercontent.com/29139697/76559895-4eee3380-64a0-11ea-87f0-7df04b2c78e5.png)

**Comment by SebastianStehle** [comment]
It is HTML, very likely that the HTML contains more than 100 characters.

Please use the support forum next time.
