### ISSUE TITLE
Open Redirection Security Bug

### ISSUE THREAD

**Issue by ramon-sanchez** [Squidex/squidex#505]
line 409 of https://github.com/Squidex/squidex/blob/master/backend/src/Squidex/Areas/IdentityServer/Controllers/Account/AccountController.cs introduces an [Open Redirection](https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html) vulnerability. An attacker can send  a specially crafted link to an unsuspecting user of a website built with Squidex (let's assume that the returnUrl querystring parameter value of "http://google.com" is a link to a malicious website) :

https://cloud.squidex.io/identity-server/account/consent?returnUrl=http://google.com

**Comment by SebastianStehle** [comment]
Hi, I have pushed a fix.
