### ISSUE TITLE
Not able to build. Any idea?

### ISSUE THREAD

**Issue by Less97** [Squidex/squidex#51]
I receive the error

  Squidex.Infrastructure -> C:\Projects\squidex\src\Squidex.Infrastructure\bin\Debug\netstandard1.6\Squidex.Infrastructure.dll
  Squidex.Infrastructure.GoogleCloud -> C:\Projects\squidex\src\Squidex.Infrastructure.GoogleCloud\bin\Debug\netstandard1.6\Squidex.Infrastructure.GoogleCloud.dll
  Squidex.Infrastructure.RabbitMq -> C:\Projects\squidex\src\Squidex.Infrastructure.RabbitMq\bin\Debug\netstandard1.6\Squidex.Infrastructure.RabbitMq.dll
  Squidex.Infrastructure.Redis -> C:\Projects\squidex\src\Squidex.Infrastructure.Redis\bin\Debug\netstandard1.6\Squidex.Infrastructure.Redis.dll
  Squidex.Core -> C:\Projects\squidex\src\Squidex.Core\bin\Debug\netstandard1.6\Squidex.Core.dll
  Squidex.Infrastructure.MongoDb -> C:\Projects\squidex\src\Squidex.Infrastructure.MongoDb\bin\Debug\netstandard1.6\Squidex.Infrastructure.MongoDb.dll
  Squidex.Infrastructure.Tests -> C:\Projects\squidex\tests\Squidex.Infrastructure.Tests\bin\Debug\netcoreapp1.1\Squidex.Infrastructure.Tests.dll
  Squidex.Events -> C:\Projects\squidex\src\Squidex.Events\bin\Debug\netstandard1.6\Squidex.Events.dll
  Squidex.Core.Tests -> C:\Projects\squidex\tests\Squidex.Core.Tests\bin\Debug\netcoreapp1.1\Squidex.Core.Tests.dll
  Squidex.Read -> C:\Projects\squidex\src\Squidex.Read\bin\Debug\netstandard1.6\Squidex.Read.dll
Schemas\SchemaDomainObject.cs(56,44): error CS1501: No overload for method 'Dispatch' takes 1 arguments [C:\Projects\squidex\src\Squidex.Write\Squidex.Write.csproj]
C:\Program Files\dotnet\sdk\1.0.4\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(92,5): error : Cannot find project info for 'C:\Projects\squidex\src\Squidex.Core\Squidex.Core.csproj'. This can indicate a missing project reference. [C:\Projects\squidex\tests\Squidex.Write.Tests\Squidex.Write.Tests.csproj]
Schemas\MongoSchemaRepository_EventHandling.cs(41,48): error CS1501: No overload for method 'Dispatch' takes 1 arguments [C:\Projects\squidex\src\Squidex.Read.MongoDb\Squidex.Read.MongoDb.csproj]
C:\Program Files\dotnet\sdk\1.0.4\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(92,5): error : Cannot find project info for 'C:\Projects\squidex\src\Squidex.Core\Squidex.Core.csproj'. This can indicate a missing project reference. [C:\Projects\squidex\tests\Squidex.Read.Tests\Squidex.Read.Tests.csproj]

**Comment by ctolkien** [comment]
Head commit had broken the build when I tried recently. It was somewhat trivial to change the code to get it to build by looking at similar methods and overloads in the same class.

This also probably highlights a need for AppVeyor or some other CI.

**Comment by Less97** [comment]
Yep, continuous integration it's always a good idea :). Will there be a fix soon? I'd really like to checking this project out, I'm looking for CMS that could integrate with Mongo in .NET core and this looks really cool. I hope to being able to build it soon! Thanks a lot anyway for the project, from the website looks really cool!

**Comment by SebastianStehle** [comment]
Hi, how do you build it? I just checked it out on my new notebook and it works.

**Comment by Less97** [comment]
Hi Sebastian,

What I did is, git clone of the repository, dotnet restore and dotnet build. 5 errors in output. I even try with VS2017. Maybe I'm missing something or I have a wrong version of .NETCore?

**Comment by SebastianStehle** [comment]
I fixed it. I pushed something to the wrong branch. Have not realized it, because I was in a hurry to catch my flight.

I definitely need some CI, but at the moment I try to keep my costs low.

**Comment by Less97** [comment]
No worries Sebastian. Thanks a lot and sorry for not being able to solve it myself. Anyway I don't know if you can do it, but I used for an app, visualstudioonline.com. It allows you very easy and  without cost to have a CI, I did it through a simple powershell script that I published here:

http://www.alessandroorlandi.com/how-to-use-visualstudioonline-ci-with-an-azure-iis-virtual-machine

I don't know maybe it's helpful. and maybe there are better free solution out there. It doesn't matter anyway, thanks for solving it!

Alessandro

**Comment by SebastianStehle** [comment]
Yeah, I also used it, and then I run out of the 4 hours build time after 1 week ;)

**Comment by Less97** [comment]
Ahaha :) Yeah, probably you need something more sophisticated, that it's
more expensive even in terms of implementation, Thanks anyway for solving
the problem. And for the project, it looks amazing to me. Thanks a lot!

Alessandro

2017-05-19 11:05 GMT+01:00 Sebastian Stehle <notifications@github.com>:

**Comment by ctolkien** [comment]
AppVeyor / Travis are free for OSS.
