### ISSUE TITLE
Noob alert: Postman setup help?

### ISSUE THREAD

**Issue by malachib** [Squidex/squidex#66]
Hey guys, I am having difficulty getting postman to interact with OAuth2 for my cloud.squidex.io site.

I've created the client credentials and everything, but I am just getting lost.  I do have some fundamental (but not expert) understanding of OAuth2.

Can someone point me where to get started?  It seems like the 'Get New Access Token' button is the only/right place to start within Postman.  I fill out the Token Auth URL, the client ID and the client secret but I still get errors "Could not complete OAuth2 login"

Please help out - thank you!

EDIT: I also get 404's for all my requests, but I presume that's because I am not auth'd yet

**Comment by SebastianStehle** [comment]
Sorry, that you had to wait: I spent some time to write an tutorial: https://docs.squidex.io/04-guides/04-postman.html

**Comment by malachib** [comment]
Perfect, exactly what I needed!  Thank you
