### ISSUE TITLE
FieldBuilder ShowInList/ShowInReferences appear to be backwards

### ISSUE THREAD

**Issue by jrlost** [Squidex/squidex#660]
While adding an extension, I noticed that the FieldBuilder appears to have two methods that are operating contrary to their names.

https://github.com/Squidex/squidex/blob/c9f578df70939ecc2031ae4533ad2779556a2254/backend/src/Squidex.Domain.Apps.Entities/Apps/Templates/Builders/FieldBuilder.cs#L65

```c#
        public FieldBuilder ShowInList()
        {
            schema.FieldsInReferences ??= new FieldNames();
            schema.FieldsInReferences.Add(field.Name);

            return this;
        }

        public FieldBuilder ShowInReferences()
        {
            schema.FieldsInLists ??= new FieldNames();
            schema.FieldsInLists.Add(field.Name);

            return this;
        }
```

**Comment by SebastianStehle** [comment]
Lol, thats stupid. Can you provide a PR?

**Comment by jrlost** [comment]
Yeah, I'll drop one on Monday morning.
