### ISSUE TITLE
Admin panel - if the specified password was invalid the user still gets created in db

### ISSUE THREAD

**Issue by pushrbx** [Squidex/squidex#67]
I tried to create a new user through the admin panel, I didn't know about the password policy and I've received the message "the password should contain xx...". I had to retry 4 times, and each time I had to come up with a new email address for the user, because the user gets created even if the password didn't meet the password policy requirements. Is this the expected behavior?

**Comment by SebastianStehle** [comment]
No, it is a bug, I have to fix it.

**Comment by pushrbx** [comment]
My solution would be the following, but I'm not sure if it's right considering the fact that the system is using CQRS:
```cs
        [HttpPost]
        [Route("user-management")]
        [ApiCosts(0)]
        public async Task<IActionResult> PostUser([FromBody] CreateUserDto request)
        {
            IUser user = null;
            try
            {
                user = await userManager.CreateAsync(userFactory, request.Email, request.DisplayName, request.Password);
                var response = new UserCreatedDto { Id = user.Id, PictureUrl = user.PictureUrl() };

                return Ok(response);
            }
            catch (ValidationException e)
            {
                if (user != null)
                    await userManager.DeleteAsync(user);
                
                throw;
            }
        }
```

**Comment by SebastianStehle** [comment]
yes, I solved it like that but in the CreateAsync method. This solution would not work, because when an ValidationException is thrown, you don't get back a user ;)

**Comment by pushrbx** [comment]
Is commit ffa844f fixes this then?

**Comment by SebastianStehle** [comment]
Yes, but I made a lot of changes recently. I would like to continue testing. I give you the okay in about 8 hours to use it ;)
