### ISSUE TITLE
Support for adding buttons and controls with webhooks to backend without coding.

### ISSUE THREAD

**Issue by vector-man** [Squidex/squidex#675]
Is there a way to add buttons to the backend without coding (from within the UI.) I need to have a button in the backend per user that when pressed, triggers a webhook to send an email to them with a template.

So, like this: Press button in backend on a user  ->  webhook is triggered -> my client sends an email to the user "here's your prize link: http://example.com John"

Is there an easy way to do this without using Node.js or coding in the backend.

**Comment by SebastianStehle** [comment]
Right now it is not possible and I have no plans to do so. The only option would be to write a rule that reacts when a flag is set to true for a user.

Then you click a checkbox and save the content.
