### ISSUE TITLE
GraphQL - Querying references result in 400 Bad request

### ISSUE THREAD

**Issue by pushrbx** [Squidex/squidex#68]
I tried to query a relationship with graphql but it has resulted in 400 Bad request error. The graphql query itself is valid, but it seems the backend can't query references.
Example:
Let's say you want to tag your articles. For each set of tags you have categories.
So you create two schema: terms and vocabularies.
```js
{
   "terms": {
        "title": "string - localizable",
        "description": "string  - localizable",
        "slug": "string"
   },
   "vocabularies": {
        "title" "string - localizable",
        "slug": "string",
        "description": "string  - localizable",
        "terms": "reference"
   }
}
```
So if I want to query the list of terms for each vocabulary, I would do the following graphql query:
```graphql
{  queryVocabulariesContents { id, data { title { en }, terms { iv { id } } } } }
```
But this one results in a bad request error. So my question would be: Is it possible to query relationships/references?

**Comment by SebastianStehle** [comment]
Thank you for the bug report. It worked for me, see https://github.com/Squidex/squidex/blob/master/tests/Squidex.Domain.Apps.Read.Tests/Contents/GraphQLTests.cs Should_also_fetch_referenced_contents_when_field_is_included_in_query

Can you send me dump of your mongo database?

**Comment by SebastianStehle** [comment]
Btw: Your query is:

query {
 {  queryVocabulariesContents { id, data { title { en }, terms { iv { id } } } } }
}

Right?

**Comment by pushrbx** [comment]
Yes it is. I will try to verify this with the unit test as soon as I can.

**Comment by pushrbx** [comment]
Yep, the test is working fine for me as well. 
Here is the mongodb dump: https://archiverbx.blob.core.windows.net/public/pushrbx_squidex_mongodb_dump.zip
