### ISSUE TITLE
API docs: Wrong documentation for /status endpoint?

### ISSUE THREAD

**Issue by mmichaa** [Squidex/squidex#684]
Hi, I'm new to Squidex - which is awesome! - but I've the feeling, that the generated documention for the /status content endpoint is wrong. See the screenshot for example:
![image](https://user-images.githubusercontent.com/68866/114567242-5370b700-9c73-11eb-803c-e73c693326be.png)

Shouldn't that correspond to the GraphQL mutation `changePageContent`, which expects `status`, `dueTime` and `expectedVersion` as payload?

**Comment by SebastianStehle** [comment]
Thats true.

**Comment by SebastianStehle** [comment]
I have pushed a fix for this problem.
