### ISSUE TITLE
CLI sync - asset folder structure not preserved

### ISSUE THREAD

**Issue by blistick** [Squidex/squidex#685]
I used the CLI to sync an existing app (the source) to a new app (the clone). Everything worked perfectly, except that the asset folder structure from the source was not preserved in the clone.

The source app has folders "audio", "images", and "xml" at the root, with the associated files found within those folders.  After sync the clone app contains all the assets, but they're all at the root, and none of the folders exist.

**Comment by SebastianStehle** [comment]
Thank you very much.

**Comment by SebastianStehle** [comment]
I have pushed a new version of the CLI.
