### ISSUE TITLE
[Angular] Error: Uncaught (in promise): ErrorResponse: login_required

### ISSUE THREAD

**Issue by pushrbx** [Squidex/squidex#71]
I have downloaded the latest version and after trying to run it I get `Error: Uncaught (in promise): ErrorResponse: login_required` uncaught exception error. This was working before. (around commit f2671286b), 

This happens on the home page, where you would login. Also it happens on the `/login` route.

![image](https://user-images.githubusercontent.com/6832715/28276431-d4f91c6c-6b0e-11e7-84cb-52db38bda833.png)

**Comment by SebastianStehle** [comment]
Thanks a lot for all your help. Which browser are you using?

I have to start with feature branches, sorry for that :(

**Comment by pushrbx** [comment]
Chromium Version 61.0.3145.0 (Official Build) (64-bit)

**Comment by SebastianStehle** [comment]
Should be fixed.

**Comment by pushrbx** [comment]
I can confirm it, it is working now.

**Comment by SebastianStehle** [comment]
Thank you. I changed too much recently:

* Migrated the code to Angular4 HttpClient
* I used Promises and Observables before and changed everything to use Observables. 
* I improved the CQRS implementation

Next time I will either use feature branches or smaller, more stable releases. I hope that we can mark the version as 1.0 in a couple of weeks and I need a concept then ;)

**Comment by pushrbx** [comment]
I recommend this read: http://nvie.com/posts/a-successful-git-branching-model/
