### ISSUE TITLE
Nub react+redux usage question: CORS

### ISSUE THREAD

**Issue by malachib** [Squidex/squidex#74]
Briefly setting aside security concerns of OAuth2 token usage on a react+redux JS client (*if* that's something that we can set aside), what might I do about:

```
Fetch API cannot load https://cloud.squidex.io/api/content/my-proj/my-data. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. 
Origin 'http://localhost:5000' is therefore not allowed access. 
If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

When using cloud.squidex.io?

It seemed that all-access CORS was enabled a few months ago in squidex itself... so I am a little lost.  Thank you in advance!

**Comment by SebastianStehle** [comment]
Mhm, I don't see the problem. I just made the following request:

	GET https://cloud.squidex.io/api/apps HTTP/1.1
	accept: application/json, text/plain, */*
	accept-encoding: gzip, deflate, br
	accept-language: *
	authorization: Bearer ...
	cache-control: no-cache
	content-type: application/json
	Host: cloud.squidex.io
	Origin: http://google.de
	
and got back:

	HTTP/1.1 200 OK
	Date: Tue, 18 Jul 2017 05:11:32 GMT
	Content-Type: application/json; charset=utf-8
	Transfer-Encoding: chunked
	Connection: keep-alive
	Access-Control-Allow-Origin: *
	Server: cloudflare-nginx
	Content-Encoding: gzip

Seems to work, doesn't it?

**Comment by malachib** [comment]
OK, that's a good sign .  I'll dig in deeper ...

**Comment by SebastianStehle** [comment]
@malachib Have you solved the problem?

**Comment by malachib** [comment]
I have not; I would consider brute forcing the headers kind of an ugly workaround so I was waiting for someone wiser than I to recommend something.  I apologize for not noticing your question earlier, usually I watch these threads like a hawk
