### ISSUE TITLE
[Question] Is the version of the asset unique on upload?

### ISSUE THREAD

**Issue by pushrbx** [Squidex/squidex#75]
I have started working on the support for azure blob storage, and I'm trying to use the snapshot feature of azure storage. While I was implementing the `IAssetStore` interface a question struck me: Is it ensured that the version of the asset on upload is unique?

```cs
public async Task UploadAsync(string id, long version, string suffix, Stream stream)
{
    var blobName = GetObjectName(id, suffix);
    var blob = blobContainer.GetBlockBlobReference(blobName);

    if (await blob.ExistsAsync())
    {
        // if it's already exist create a snapshot, and we overwrite the source blob of the snapshot.
        // Doubt: if the version is already exist this will throw an exception
        await CreateVersioningSnapshotAsync(blob, id, version);
    }

    if (!blob.Metadata.ContainsKey(AssetVersion))
        blob.Metadata.Add(AssetVersion, version.ToString());
    else
        blob.Metadata[AssetVersion] = version.ToString();

    blob.Metadata[AssetId] = id;
            
    await blob.UploadFromStreamAsync(stream);
    await blob.SetMetadataAsync();
}

private async Task CreateVersioningSnapshotAsync(CloudBlockBlob blob, string id, long version)
{
    var metadata = new Dictionary<string, string>();
    metadata.Add(AssetVersion, version.ToString());
    metadata.Add(AssetId, id);
    await blob.CreateSnapshotAsync(metadata,
        null, null, null);
}
```

**Comment by SebastianStehle** [comment]
It should be unique. I actually realized that 2 users could update the same asset. Then you would not know, who wins. But It think we can ignore it for now. And then the proper solution would be to extend the interface with a rename method. So that we can upload to a temporary file first and then rename or delete it.

**Comment by SebastianStehle** [comment]
Something like:

    public interface IAssetStore
    {
        Task DownloadAsync(string id, long version, string suffix, Stream stream);

        Task UploadAsync(string id, long version, string suffix, Stream stream);
		
        Task PrepareUploadAsync(Guid commitId, Stream stream);
        
        Task CommitUploadAsync(Guid commitId, string id, long version, string suffix);
		
        Task AbortUploadAsync(Guid commitId);
    }
