### ISSUE TITLE
Use the Angular CLI for the UI

### ISSUE THREAD

**Issue by DavidRouyer** [Squidex/squidex#80]
The [Angular CLI](https://github.com/angular/angular-cli) is a amazing tool with a ton of features. Plus, you don't need to manage the webpack configuration yourself.
I've tried the UI with both npm and yarn and it breaks some parts of the code (JS dependency management is a nightmare). I would like to fix the bugs but TypeScript sourcemaps are not configured. I'm working with the CLI for several months and it provides everything you need without worrying for the config.

Tell me if you're interested, I can provide a pull request.

**Comment by SebastianStehle** [comment]
Hi, when I started with the Angular UI the CLI was not stable yet. 

Now I have a setup where I am very happy with. Angular CLI makes some things different, e.g. how imports are managed. 

When other developers will contribute to the code I am open to start the discussion again, e.g. if we should change the way we manage imports and if we should switch to Angular CLI. At the moment I don't see any good reasons to spend time for that.

**Comment by SebastianStehle** [comment]
@DavidRouyer I think for Angular5 it could be interesting, because it seems that they changed the compiler structure and got rid of the non-AOT path.

**Comment by DavidRouyer** [comment]
I don't see any reason not doing it :)

**Comment by SebastianStehle** [comment]
No, me neither ;)

**Comment by SebastianStehle** [comment]
@DavidRouyer Are you still motivated to help with that? 

Just read this article: https://medium.com/@tomastrajan/6-best-practices-pro-tips-for-angular-cli-better-developer-experience-7b328bc9db81

**Comment by DavidRouyer** [comment]
Sure, but if you want to use Angular CLI 1.5 you'll need to upgrade the app to Angular 5 :)

**Comment by SebastianStehle** [comment]
I know, I am fine with that. Afaik there is nothing that should break. I already mirgated to the new HttpClient.

**Comment by maxisam** [comment]
this is an old thread but I think you can try nx https://nx.dev/latest/angular/core-concepts/nx-devkit if you want to switch to angular cli.

It will save you lot of time on build/lint/etc and provide incremental build. 

And it also setup cypress and storybook for you.

However, it will be a big process to switch to it. 

Anyway, I love your work. Our company is looking for a good headless CMS. So far I think yours is the best for us.

**Comment by SebastianStehle** [comment]
PRs are definitely welcome, but at the moment everything works as it should :)

**Comment by SebastianStehle** [comment]
Thx for closing it. Yes it is done now.

**Comment by maxisam** [comment]
This is awesome! In case you are interesting, I like NX better now. https://nx.dev/

It takes care tool chain upgrade and integration
