### ISSUE TITLE
Content API: Add mutations for GraphQL

### ISSUE THREAD

**Issue by DavidRouyer** [Squidex/squidex#81]
The GraphQL endpoint of the Content API is read only (only queries). It would be nice if it was on par with the REST endpoint by adding mutations.

**Comment by SebastianStehle** [comment]
@DavidRouyer We are preparing the subscription management now. After that we will improve the webhooks a little bit and then Mutations has one of the highest prioritities.

**Comment by SebastianStehle** [comment]
The priorities changed a lot, but I started with it now. My main problem are restrictions in graphql-dotnet :(

**Comment by SebastianStehle** [comment]
https://github.com/graphql-dotnet/graphql-dotnet/issues/527

**Comment by SebastianStehle** [comment]
In progress: https://github.com/Squidex/squidex/pull/222
