### ISSUE TITLE
GetEventStore projections Ssl support?

### ISSUE THREAD

**Issue by pushrbx** [Squidex/squidex#83]
Currently only http requests are being done to the geteventstore's api. It would be great if it could be configured to do the api calls through ssl. This is a simple change i guess. It only requires an extra config option in the appsettings file, and in the EventStoreModule the code should check for this config and setup the connection object accordingly. 
http://docs.geteventstore.com/server/4.0.0/setting_up_ssl_linux/

The reason for this feature request is that I'd like to secure my setup by opening as few as possible ports on my server. I have a nginx proxy which is enforcing ssl and adds hsts headers in the responses, and it forwards requests to the appropriate docker containers based on vhosts.

**Comment by SebastianStehle** [comment]
The connection string seems to support it: http://docs.geteventstore.com/dotnet-api/4.0.0/connecting-to-a-server/

**Comment by pushrbx** [comment]
Uh it seems I have mixed things up a bit. Let me clarify: Last night I was trying to make the system connect to the projections api through ssl, and ultimately through my nginx proxy. But it didn't work, so I ended up opening the 2113 port and I have set the IP of my server as projection host in the appsettings. I thought that the projectionHost config item belongs to the setup of the geteventstore connection. It seems it's not.

**Comment by SebastianStehle** [comment]
It is very strange in the EventStoreClient i think. The projectionmanager API has its own configuration. Don't know why. 

But in a docker environment you don't need it. As long as the containers share the network you can connect to EventStore from Squidex even when you don't make the port public (only expose it).

**Comment by pushrbx** [comment]
yeah, but the problem is that squidex is running on a azure appservice, and I run the geteventstore on a vm, and I can't create a vnet between them because they are on two different subscriptions. (I got a coupon code for appservices :P )
So the solution is a vnet in my case. I will poke around this projections api to find why it has different connection mechanism. I hoped you might know something about it.
