### ISSUE TITLE
Source code for Squidex.ClientLibrary

### ISSUE THREAD

**Issue by andrerav** [Squidex/squidex#836]
Hi,

I am looking for the source code for [Squidex.ClientLibrary](https://www.nuget.org/packages/Squidex.ClientLibrary/). The NuGet site points back to this repository, but I can't for the life of me find the actual source code. Could you please enlighten me? :) 

Thanks,
Andreas

**Comment by SebastianStehle** [comment]
Sure, it is here: https://github.com/Squidex/squidex-samples/tree/master/csharp/Squidex.ClientLibrary

**Comment by andrerav** [comment]
Great, thank you!
