### ISSUE TITLE
Is it possible to create read only api client?

### ISSUE THREAD

**Issue by pushrbx** [Squidex/squidex#84]
Would it be possible with the current version of squidex to create an api client with read only scope/rights?

**Comment by SebastianStehle** [comment]
Not yet. Should be relatively easy to implement it. I am not sure how I want to implement the permission system yet. Everything seems to be either super complicated or very limiting for me ;)

**Comment by pushrbx** [comment]
The permission system I'm looking for is the following;
The client app can access most of the contents, but can't write to them. Write access would only be granted if the user is authenticated and has the required roles to write. Also there would be schemas which can be only read if the user is authenticated and has the required roles.

So the administrator should be able to assign roles to the created clients.
I'm not sure how easy this is, but I don't think it's too difficult. Look at the jwt given by IdentityServer:
Authenticated user:
```json
{
  "nbf": 1501064974,
  "exp": 1501068574,
  "iss": "https://cloud.squidex.io",
  "aud": [
    "https://cloud.squidex.io/resources",
    "squidex-api"
  ],
  "client_id": "squidex-frontend",
  "sub": "59777bd81899d726c05fe4b3",
  "auth_time": 1501061432,
  "idp": "Google",
  "role": "ADMINISTRATOR",
  "scope": [
    "openid",
    "profile",
    "squidex-profile",
    "role",
    "squidex-api"
  ],
  "amr": [
    "external"
  ]
}
```
Simple client created for an app:
```json
{
  "nbf": 1501064634,
  "exp": 1503656634,
  "iss": "https://cloud.squidex.io",
  "aud": [
    "https://cloud.squidex.io/resources",
    "squidex-api"
  ],
  "client_id": "test1:postman-test",
  "scope": [
    "squidex-api"
  ]
}
```

So it only needs a role to be assigned, and we just remove the `MustBeAppEditor` attribute from above the `ContentsController` and add more specific attributes per action I guess.
I could think of a configurable system, where the custom Authorization attribute would read the config and apply it on the current action, but that one is too complicated for now.

**Comment by SebastianStehle** [comment]
A read-only client is very straight forward. I will definitely implement that for v1. I will just add a new role "Reader" and check for this role.

But more advanced features are harder to implement. e.g. you could have a client that can only write to specific schema. You could solve the most stuff in the UI, but not everything. My idea is to add a script engine for more complicated stuff, e.g. "You can only change a content, when the [IsClosed]=false" or so.

**Comment by pushrbx** [comment]
Yeah with the read-only client I could build an UI which uses multiple apps within squidex to achieve the permission system what I'm looking for. I would only have to write some code to automatically assign users 
 as contributors to the secondary app with the restricted stuff. The UI would have to be able to change between the read only client token and the authenticated user's token.
