### ISSUE TITLE
[Bug 6.6.0] Performance killing client(front-end) error

### ISSUE THREAD

**Issue by thepra** [Squidex/squidex#859]
![immagine](https://user-images.githubusercontent.com/7032509/160246611-d7346be4-444d-4ad9-8a12-8fe2d87454df.png)
as in the image this error log is being spammed non-stop in the backup page meanwhile/after starting a backup, making the client interminently unresponsive

**Comment by SebastianStehle** [comment]
Thanks. I will have a look tomorrow.

**Comment by SebastianStehle** [comment]
I cannot reproduce it :(
