### ISSUE TITLE
OData: Filtering by references

### ISSUE THREAD

**Issue by pushrbx** [Squidex/squidex#87]
The schema:
```json
{
   "term": {
        "title": "string - localizable",
        "description": "string  - localizable",
        "slug": "string",
        "vocabulary": "reference"
   },
   "vocabulary": {
        "title": "string - localizable",
        "slug": "string",
        "description": "string  - localizable",
   }
}
```
The uri with the query:
`http://localhost:3000/api/content/sampleapp/term?$filter=data/vocabulary/iv/any(d:d/id eq e46aca5e-5067-408f-b90f-ea441314385a)`

But the server response is always:
```json
{
    "message": "Failed to parse query: Could not find a property named 'vocabulary' on type 'Squidex.Term'.",
    "details": [],
    "statusCode": 400
}
```

I'm not sure about the `d/id` bit, but I've seen that within the `iv` property the array has objects with `id` properties.
Also I can see that operators like `$expand` and `$select` are not supported.

Is there any alternative way to achieve this query on the database through odata?

**Comment by SebastianStehle** [comment]
Not yet, I will fix it today.

**Comment by pushrbx** [comment]
Isn't this related to the fact that the ReferenceField.CreateEdmType returns null?

**Comment by SebastianStehle** [comment]
Yes, it is. I was not sure how to implement it in an easy way. I think I will not follow the OData path here and just use the eq and ne operator.

**Comment by pushrbx** [comment]
Does that mean, that even if I use eq or ne, it would do the search in the array of references, despite that the standard says that this should be achieved through `any`?

**Comment by SebastianStehle** [comment]
Yes, I don't remember the full specification, but the any operator is so complicated and also slow when and problematic when you want to implement it the full way.

**Comment by pushrbx** [comment]
This solution is fine for me.  😄

**Comment by SebastianStehle** [comment]
Btw: I have added you as contributor to the Readme.md...I hope it is fine

**Comment by pushrbx** [comment]
I've seen it, it's ok.

**Comment by pushrbx** [comment]
\o/ cheers

**Comment by pushrbx** [comment]
This one also needs documentation. Now I don't know how to do the query. That's true that it has stopped complaining about the reference field, but I don't know what is the correct syntax. When I do a graphql query, I see that the partitioning field is an array.
```json
{
  "data": {
    "queryTermContents": [
      {
        "id": "fa9ca9d2-0448-4a6e-9afe-f37cb4905d49",
        "data": {
          "title": {
            "en": "shoe"
          },
          "slugId": {
            "iv": 1
          },
          "vocabulary": {
            "iv": [
              {
                "id": "e46aca5e-5067-408f-b90f-ea441314385a",
                "data": {
                  "title": {
                    "en": "category",
                    "de": "kategorie"
                  }
                }
              }
            ]
          }
        }
      }
    ]
  }
}
```
So  based on this I tried
`$filter=data/vocabulary/iv/any(d:d/id eq 'e46aca5e-5067-408f-b90f-ea441314385a')`
But the server returns:
```json
{
    "message": "Failed to parse query: Can only bind segments that are Navigation, Structural, Complex, or Collections. We found a segment 'iv' that isn't any of those. Please revise the query.",
    "details": [],
    "statusCode": 400
}
```

**Comment by SebastianStehle** [comment]
I know, was too late yesterday evening ;)

Just a normal eq query:
$filter=data/vocabulary/iv eq 'e46aca5e-5067-408f-b90f-ea441314385a'

**Comment by pushrbx** [comment]
Cheers. I'll sketch a draft for the docs about this.

**Comment by SebastianStehle** [comment]
You can make a pull request if you want: https://github.com/Squidex/squidex-docs

**Comment by pushrbx** [comment]
Sent: https://github.com/Squidex/squidex-docs/pull/1
