### ISSUE TITLE
[GetEventStore] Event Consumers stop on their own after some time.

### ISSUE THREAD

**Issue by pushrbx** [Squidex/squidex#88]
Every now and then the event consumers just stop with the error message `EventStore.ClientAPI.Exceptions.ConnectionClosedException: Subscription closed with reason UserInitiated.`
Is it possible to prevent this behavior? Am I configuring something wrong?
For now I've solved it with an automatic job which restarts the event consumers when they are down.

**Comment by SebastianStehle** [comment]
Thank you very much. What means "after some time"? Can I reproduce it?

**Comment by pushrbx** [comment]
I don't know how to reproduce it, it just happens on it's own. Also it's worth mentioning that I run squidex in a Azure Web app with AlwaysOn turned on. Also on my linux vm I have set the tcp TTL to 500ms, because I had similar problem with mongodb as an eventstore, and in that case this change could cure it.

**Comment by SebastianStehle** [comment]
Do you have the logs from GetEventStore for me?

**Comment by SebastianStehle** [comment]
The UserInitiated reason only happens when you stop a subscription, which could be either happen by an bug when you stop a subscription or when the app is shutdown. I fixed it and also implemented some retry mechanism for reconnecting a subscription.

**Comment by pushrbx** [comment]
just for future reference: if you ask for log files of `geteventstore`, which logs do you mean, and how can I retrieve them?
