### ISSUE TITLE
Sample app with UI

### ISSUE THREAD

**Issue by papyr** [Squidex/squidex#907]
Hello I find this project very interesting I've been trying to follow it.

May I kindly request a sample of web UI asp mvc views bs5, user admin, especially around partial views/etc so we can build applications with dashboards and easy path to some tables for transactional crud data.

For several developers it go a long way as a reference application

**Comment by SebastianStehle** [comment]
Hi, there are a few small sample applications here: https://github.com/Squidex/squidex-samples/tree/master/csharp

I am not entirely sure what you are looking for, though.

**Comment by papyr** [comment]
Hello @SebastianStehle thanks for that link ☘️ very nice CMS btw, 💯 , that was what I was looking for, actually your CMS could be a good "Self marketing tool" for something like micro social CMS use case, where people in a community (carpenters, can share posts, designes, likes ask questions.

I was trying to replace some of that with your CMS, ABP is a night mare, so I thought this was much easier. Thanks again.

Do you have a chat sometime to discuss these ideas

**Comment by SebastianStehle** [comment]
Only the support forum: https://support.squidex.io

**Comment by SebastianStehle** [comment]
Thanks for your nice words, btw
