### ISSUE TITLE
Assets should have an option to have external links in case of external asset storage

### ISSUE THREAD

**Issue by pushrbx** [Squidex/squidex#91]
If the asset store is set to an external service e.g. google cloud or azure storage, they should have an option to allow the linking from the external service.

**The current behavior is the following:**
When the client uploads the asset, the asset will get an Id, the asset gets uploaded to the external service and it can be requested from the squidex api via its Id. During the request the asset gets downloaded on the webserver and then returned to the client.

**Desired behavior:**
When the client uploads the asset, the asset will get an Id, the asset gets uploaded to the external service. When it gets requested with its Id from the squidex api, the api returns the url to the asset on the external service. In case of Azure Storage it would return something like `https://azurestorageaccount1.blob.core.windows.net/squidex/assetid.jpg` and the client would be responsible to fetch the asset from the given url. This behavior should be optional, and it could be set via a checkbox during schema creation.

**Comment by ctolkien** [comment]
One other scenario to consider. We sometimes use private azure blobs with a short lived SAS token to allow access (for instance, with a 1 minute lifetime - enough time for a client to download the resource).

**Comment by SebastianStehle** [comment]
I don't see the use case yet to be honest. Do you have doubts about performance? When the file is not an image or already exists in the expected dimensions nothing is downloaded. It is just streamed to the client, which is a relatively cheap operation. Of course you have the overhead of 20ms or so to fetch the asset information from MongoDb.

The reason why I did it this way is to be able to implement advanced security mechanisms.  For the cloud version it would also mean that I have to make the whole storage public. I could make a setting to turn it on for your private installations. Do you just want to have the url after an upload?

**Comment by pushrbx** [comment]
> Do you just want to have the url after an upload?

No. I want the url in the response object when I query for a document which has an asset field. 

> It is just streamed to the client, which is a relatively cheap operation.

Oh, I didn't consider that. But in case of azure I think you get charged twice because the data flows from the blob storage to the app service instance and from there to the client. Of course the first 5gb of bandwidth is free, but after that it can mean something.  Could this be negligible?

>  I could make a setting to turn it on for your private installations.

I forgot to include this. Yes, this would be nice.

So in overall my concern is performance and cost.
Sorry for being nit picky I just like considering all my options. 😄

**Comment by SebastianStehle** [comment]
About the costs: I think you always have to pay for outbound traffic, even if it is coming from azure blob, but I could be wrong.

In general I can do it, but I need some kind of a enrichment pipeline first. For GraphQL endpoint such a pipeline already exists and it would be easy to integrate it there.

**Comment by pushrbx** [comment]
I was saying that from azure blob to the managed VM is also an outbound traffic, and from the managed VM (app service) to the browser is also an outbound traffic. If an url is being returned to the blob, this will be reduced to a trip from the blob storage to the browser.

**Comment by SebastianStehle** [comment]
My understanding is that if your VM and the blob storage are in the same data center it is not outbound traffic.

**Comment by pushrbx** [comment]
I will have to dig into this. 😕

**Comment by SebastianStehle** [comment]
GraphQL is the perfect example for this case. For the normal content API I would have a to define a custom enrichment syntax and so on.

I can definitely do it, the question is just if I have to. The best code is No code ;)

**Comment by SebastianStehle** [comment]
There is a sourceUrl field in GraphQL now.
