### ISSUE TITLE
Google Login 400

### ISSUE THREAD

**Issue by khusseini** [Squidex/squidex#93]
Hello hello :)
Wonderful CMS you have built there, I am currently in the process of integrating it into our infrastructure.
I have, however two issues with the current system:

1. When trying to login or sign up using google, I get an HTTP error 400 :/ this is new actually as last week a fresh docker image was working perfectly fine
2. Is it possible to only allow users who were invited to login? Is there some kind of root user that can configure everything? Maybe through a configuration file that I can mount into the docker container to be read on start up?

Best regards and keep up the great work.

**Comment by SebastianStehle** [comment]
Hi,
thank you for your warm words :)

I have no idea what went wrong with the Google login. Do you have logs with errors? Perhaps a wrong config or have you changed your domain? How do you deploy Squidex?  Manually or with docker compose?

About your other question: Please have a look to the appsettings file:

https://raw.githubusercontent.com/Squidex/squidex/master/src/Squidex/appsettings.json All settings can also be overriden with Environment variables. See https://github.com/Squidex/squidex-docker/blob/master/standalone/docker-compose.yml. This is a ready to use environment with Https and password authentication. Just make your changes in the .env file and deploy it :)

1. The first user becomes administrator automatically. You cannot change it with the UI yet, but of course you can just go to the database and add the Administrator Role to your users.
2. You can use lockAutomatically to lock new users. Then you have to unlock them before they can use Squidex.
3. You can use email authentication only. You get the admin user automatically (see the docker-compose file) and can then create new users in the administration section.

**Comment by khusseini** [comment]
Thank you for the prompt response :)
As for the google 400 error, reason was that I used a non public URL as my `SQUIDEX_DOMAIN` and `SQUIDEX_BASE_URL`. So it was a configuration mistake on my side.

Wonderful that we can configure the app through json and environment variables.
Thanks again for your help.

**Comment by SebastianStehle** [comment]
Yeah, I also like the new configuration model from ASP.NET Core :)
