### ISSUE TITLE
Content PUT method is throwing an error 'Failed to update content. Please reload.'

### ISSUE THREAD

**Issue by Avd6977** [Squidex/squidex#94]
There was code added to contents.service.ts about 4 days ago
        return HTTP.putVersioned(this.http, url, dto, version)
                .do(content => {
                    this.localCache.set(`content.${content.id}`, content, 5000);
                })
                .pretifyError('Failed to update content. Please reload.');

The 'content' is null because the controller response is a 204 No Content so it throws a null exception when updating the cache.

**Comment by SebastianStehle** [comment]
Thank you very much.
