### ISSUE TITLE
Any plan to support .net core 2.0

### ISSUE THREAD

**Issue by darting** [Squidex/squidex#97]
Hi guys,

Do you have any plan to support .net core 2.0?

Thanks

**Comment by SebastianStehle** [comment]
Yeah, definitely. Tomorrow I will be on vacation for 2 weeks, but has very priority to migrate i to .net core in September. Some of the libraries we use must be migrated as well, e.g. identity server or NSwag.

**Comment by SebastianStehle** [comment]
Migrated to .NET Core 2.0 (but not ASP.NET Core 2.0 yet)
