### ISSUE TITLE
Questions about some principles

### ISSUE THREAD

**Issue by hezhongfeng** [Squidex/squidex#989]
1. I want to know, for each schemas created, the database created a table?
2. When I modify schemas, does the table structure also change with it?
3. How is my ccontent stored in the database?

Where can I get this knowledge

**Comment by d-Pixie** [comment]
@hezhongfeng considering Squidex is backed by MongoDB I'd guess that the schemas are stored as collections there. Instances of the schemas are stored as separate collections.

Try to inspect the Mongo instance using the dashboard to see what data has been created. But I'm guessing it's not a great idea to manually edit that data if you want the app to keep working 🙂
