### ISSUE TITLE
not able to install Squidex

### ISSUE THREAD

**Issue by siddharthgaur2590** [Squidex/squidex#994]
Hi Team and @sangramrath , @SebastianStehle, @kamushadenes , @seamys 

I'm trying to install Squidex on K8s cluster individually where MongoDB is already installed and up and running. I used the deployment yamls as mentioned in your github(https://github.com/Squidex/squidex/tree/master/helm/squidex7) but constantly getting:

Unhandled exception. System.Net.Sockets.SocketException (13): Permission denied
2023-05-13T09:27:42.565Z |    at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)

Can you please suggest something.

Thanks

**Comment by SebastianStehle** [comment]
Please create a ticket in the support forum: https://support.squidex.io
