### ISSUE TITLE
Tags on schemas not saved

### ISSUE THREAD

**Issue by d-Pixie** [Squidex/squidex#996]
In a fresh install of Squidex, using the v7 helm chart, I'm playing around with the tags field that exists on a schema and each field in the schema. I can get it to show a tag in the box as expected, but when I try to save I get a "Nothing has changed" message and reloading the schema the tag field is empty again. If I try to change some other property and save, to avoid it thinking there is no change, it doesn't save the tags then either.

![ScreenFlow](https://github.com/Squidex/squidex/assets/1247102/b7b21791-a914-4867-8660-bc665ad38ce8)

**Comment by SebastianStehle** [comment]
Thx. I will test that out.

**Comment by SebastianStehle** [comment]
I cannot reproduce it yet. How do you add the tag? Do you press Enter or comma?

**Comment by d-Pixie** [comment]
@SebastianStehle I used comma. I'll try enter now ... Didn't work either.

I have tested this on an entire schema, the main settings for the markdown component for example, and on a field in a schema.

**Comment by SebastianStehle** [comment]
Which browser do you use? Is there any error I'm the browser logs?

**Comment by SebastianStehle** [comment]
Can you check the version of the squidex container? Does the hash match to the latest 7.x version?

**Comment by d-Pixie** [comment]
I don't get any errors while adding tags och trying to save. But when I switch between views I get this a bunch of times: 
![Screenshot 2023-06-15 at 16 45 04](https://github.com/Squidex/squidex/assets/1247102/5e620d96-1eb0-4cdd-a601-6c58253b3735)

I'm using latest Chrome on Mac. The container says it's running squidex/squidex:7.0.2 with hash e4c424c1a08d5433415dea4c6d66a24660c3e1cd33b3d0e36171a19457bc64ee

**Comment by SebastianStehle** [comment]
Can you upgrade?

**Comment by d-Pixie** [comment]
Upgraded to 7.6.1, the problem is fixed.

Since the helm chart defaulted to 7.0.2, instead of the latest version, should I open a ticket for that issue?

**Comment by SebastianStehle** [comment]
I can fix that. Thx.

**Comment by d-Pixie** [comment]
Thanks.

Sorry it wasn't obvious that the helm chart didn't use the latest version 🙂 Otherwise I would probably have tried that first ...
